# Generated by Django 6.0.8 on 2026-09-19 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        ('core', '0006_move_category_to_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='categories',
            field=models.ManyToManyField(blank=True, db_table='videos_league_categories', help_text='Categorías de la liga (puede ser múltiple para torneos/copas)', related_name='leagues', to='core.category'),
        ),
        migrations.AlterField(
            model_name='league',
            name='category',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Usar categories', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues_old', to='core.category'),
        ),
    ]
