# Generated by Django 6.0.8 on 2026-09-20 14:47
# Ajustada a mano: añade temporada a los roles de plantilla, reasigna los
# roles existentes a la temporada anterior (la pasada) y rehace los
# constraints únicos para que sean por temporada.

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone

from videosvoley.core.models import season_start_year_for_date


def backfill_previous_season(apps, schema_editor):
    PlayerRole = apps.get_model('rosters', 'PlayerRole')
    StaffRole = apps.get_model('rosters', 'StaffRole')
    player_roles = PlayerRole.objects.filter(season__isnull=True)
    staff_roles = StaffRole.objects.filter(season__isnull=True)
    if not (player_roles.exists() or staff_roles.exists()):
        return
    Season = apps.get_model('core', 'Season')
    start_year = season_start_year_for_date(timezone.now()) - 1
    name = f'{start_year}-{(start_year + 1) % 100:02d}'
    season, _ = Season.objects.get_or_create(
        name=name,
        defaults={'start_year': start_year, 'end_year': start_year + 1},
    )
    player_roles.update(season=season)
    staff_roles.update(season=season)


def reverse_backfill(apps, schema_editor):
    # Las columnas de temporada se eliminan al revertir; no hay nada que restaurar.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_season'),
        ('rosters', '0004_delete_legacy_player_staff'),
        ('teams', '0002_alter_team_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playerrole',
            name='unique_active_player_role',
        ),
        migrations.RemoveConstraint(
            model_name='playerrole',
            name='unique_jersey_number_per_team',
        ),
        migrations.RemoveConstraint(
            model_name='staffrole',
            name='unique_active_staff_role',
        ),
        migrations.AddField(
            model_name='playerrole',
            name='season',
            field=models.ForeignKey(blank=True, help_text='Temporada en la que el jugador pertenece al equipo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_roles', to='core.season', verbose_name='Temporada'),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='season',
            field=models.ForeignKey(blank=True, help_text='Temporada en la que la persona desempeña el rol', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_roles', to='core.season', verbose_name='Temporada'),
        ),
        migrations.RunPython(backfill_previous_season, reverse_backfill),
        migrations.AddConstraint(
            model_name='playerrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('person', 'team', 'season'), name='unique_active_player_role'),
        ),
        migrations.AddConstraint(
            model_name='playerrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('jersey_number__isnull', False)), fields=('team', 'season', 'jersey_number'), name='unique_jersey_number_per_team'),
        ),
        migrations.AddConstraint(
            model_name='staffrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('person', 'team', 'role', 'season'), name='unique_active_staff_role'),
        ),
    ]
