# Generated by Django 5.2.7 on 2025-11-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='response_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Tiempo de Respuesta (segundos)'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='response_type',
            field=models.CharField(blank=True, choices=[('rag_success', 'RAG Exitoso'), ('rag_fallback', 'RAG con Fallback'), ('direct_query', 'Consulta Directa'), ('timeout', 'Timeout')], max_length=20, null=True, verbose_name='Tipo de Respuesta'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user_rating',
            field=models.IntegerField(blank=True, choices=[(1, '👎 Mal'), (2, '👍 Bien')], null=True, verbose_name='Valoración del Usuario'),
        ),
    ]
