# Generated by Django 6.0.8 on 2026-09-19 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('videos', '0039_move_teams_to_app'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='League',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=200)),
                        ('federation_id', models.CharField(max_length=200, unique=True)),
                        ('competition_type', models.CharField(choices=[('regular', 'Liga Regular'), ('playoff', 'Playoff'), ('cup', 'Copa'), ('friendly', 'Amistoso')], default='regular', max_length=20)),
                        ('season', models.CharField(max_length=20)),
                        ('is_active', models.BooleanField(default=True)),
                        ('visibility_type', models.CharField(choices=[('main', 'Principal (mostrar en app)'), ('reference', 'Referencia (solo admin)'), ('historical', 'Histórica (solo admin)'), ('external', 'Externa (solo admin)')], default='main', help_text='Controla dónde se muestra la liga: Principal (en la app), Referencia (solo admin), Histórica (datos antiguos), Externa (otras ligas)', max_length=20)),
                        ('is_historical', models.BooleanField(default=False, help_text='Indica si es una liga de temporadas anteriores')),
                        ('is_our_team_related', models.BooleanField(default=True, help_text='Indica si esta liga está relacionada con nuestro equipo')),
                        ('match_format', models.CharField(choices=[('standard', 'Estándar (5 sets, ganar 3)'), ('alevin_balear', 'Alevín Balear (3 sets, jugar los 3)'), ('tournament_3sets', 'Torneo 3 sets (ganar 2)'), ('custom', 'Personalizado')], default='standard', help_text='Formato de partido para esta liga', max_length=20)),
                        ('custom_max_sets', models.IntegerField(blank=True, help_text='Máximo de sets (solo si formato es personalizado)', null=True)),
                        ('custom_sets_to_win', models.IntegerField(blank=True, help_text='Sets necesarios para ganar (solo si formato es personalizado)', null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('base_url', models.URLField(default='https://www.voleibolib.net')),
                        ('phase_name', models.CharField(blank=True, help_text='Nombre de la fase (ej: "Liguilla Oro", "Liguilla Plata", "Playoffs")', max_length=100)),
                        ('phase_order', models.IntegerField(default=0, help_text='Orden de la fase (0 = liga principal, 1+ = fases subsecuentes)')),
                        ('display_name_override', models.CharField(blank=True, help_text='Nombre personalizado para mostrar (opcional)', max_length=200)),
                        ('categories', models.ManyToManyField(blank=True, db_table='videos_league_categories', help_text='Categorías de la liga (puede ser múltiple para torneos/copas)', related_name='leagues', to='videos.category')),
                        ('category', models.ForeignKey(blank=True, help_text='DEPRECATED: Usar categories', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues_old', to='videos.category')),
                        ('parent_league', models.ForeignKey(blank=True, help_text='Liga padre si esta es una fase (ej: Liguilla Oro es fase de Liga Regular)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='competitions.league')),
                    ],
                    options={
                        'verbose_name': 'Liga',
                        'verbose_name_plural': 'Ligas',
                        'db_table': 'videos_league',
                        'ordering': ['-created_at'],
                        'unique_together': {('federation_id', 'season')},
                    },
                ),
                migrations.CreateModel(
                    name='Match',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('home_team_text', models.CharField(blank=True, help_text='Nombre del equipo local para partidos amistosos sin equipo en BD', max_length=200)),
                        ('away_team_text', models.CharField(blank=True, help_text='Nombre del equipo visitante para partidos amistosos sin equipo en BD', max_length=200)),
                        ('is_friendly', models.BooleanField(default=False, help_text='Indica si es un partido amistoso creado manualmente')),
                        ('match_date', models.DateTimeField()),
                        ('venue', models.CharField(blank=True, max_length=200)),
                        ('city', models.CharField(blank=True, max_length=100)),
                        ('round_number', models.IntegerField(default=1)),
                        ('home_score', models.IntegerField(blank=True, null=True)),
                        ('away_score', models.IntegerField(blank=True, null=True)),
                        ('status', models.CharField(choices=[('scheduled', 'Programado'), ('in_progress', 'En Progreso'), ('finished', 'Finalizado'), ('postponed', 'Aplazado'), ('cancelled', 'Cancelado'), ('withdrawn', 'Retirado (equipo fuera de liga)')], default='scheduled', max_length=20)),
                        ('federation_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                        ('referee1', models.CharField(blank=True, max_length=200, verbose_name='Árbitro 1')),
                        ('referee2', models.CharField(blank=True, max_length=200, verbose_name='Árbitro 2')),
                        ('scorer', models.CharField(blank=True, max_length=200, verbose_name='Anotador')),
                        ('timekeeper', models.CharField(blank=True, max_length=200, verbose_name='Cronometrador')),
                        ('delegate', models.CharField(blank=True, max_length=200, verbose_name='Delegado')),
                        ('field_address', models.CharField(blank=True, max_length=500, verbose_name='Dirección del Campo')),
                        ('federation_club_local_id', models.CharField(blank=True, max_length=50, verbose_name='ID Club Local (Federación)')),
                        ('federation_club_away_id', models.CharField(blank=True, max_length=50, verbose_name='ID Club Visitante (Federación)')),
                        ('acta_html', models.CharField(blank=True, max_length=200, verbose_name='Acta HTML')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team')),
                        ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team')),
                        ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.league')),
                    ],
                    options={
                        'verbose_name': 'Partido',
                        'verbose_name_plural': 'Partidos',
                        'db_table': 'videos_match',
                        'ordering': ['match_date'],
                    },
                ),
                migrations.CreateModel(
                    name='ScrapingEndpoint',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('endpoint_type', models.CharField(choices=[('standings', 'Clasificación'), ('results', 'Resultados'), ('calendar', 'Calendario'), ('json_results', 'Resultados JSON')], max_length=20)),
                        ('url_pattern', models.CharField(help_text='Usar {league_id}, {round}, etc. para parámetros dinámicos', max_length=500)),
                        ('parser_type', models.CharField(choices=[('table_standings', 'Tabla de Clasificación'), ('match_results', 'Resultados de Partidos'), ('match_calendar', 'Calendario de Partidos'), ('json_matches', 'Partidos JSON (próximos)'), ('json_results', 'Resultados JSON (finalizados)'), ('json_unified', 'JSON Unificado (configurable)')], max_length=30)),
                        ('is_active', models.BooleanField(default=True)),
                        ('extra_params', models.JSONField(blank=True, default=dict, help_text='Parámetros adicionales como JSON')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='competitions.league')),
                    ],
                    options={
                        'verbose_name': 'Endpoint de Scraping',
                        'verbose_name_plural': 'Endpoints de Scraping',
                        'db_table': 'videos_scrapingendpoint',
                        'unique_together': {('league', 'endpoint_type')},
                    },
                ),
                migrations.CreateModel(
                    name='Standing',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('position', models.IntegerField()),
                        ('played', models.IntegerField(default=0)),
                        ('won', models.IntegerField(default=0)),
                        ('lost', models.IntegerField(default=0)),
                        ('sets_for', models.IntegerField(default=0)),
                        ('sets_against', models.IntegerField(default=0)),
                        ('points_for', models.IntegerField(default=0)),
                        ('points_against', models.IntegerField(default=0)),
                        ('total_points', models.IntegerField(default=0)),
                        ('wins_3_0', models.IntegerField(default=0, verbose_name='Victorias 3-0')),
                        ('wins_3_1', models.IntegerField(default=0, verbose_name='Victorias 3-1')),
                        ('wins_3_2', models.IntegerField(default=0, verbose_name='Victorias 3-2')),
                        ('losses_2_3', models.IntegerField(default=0, verbose_name='Derrotas 2-3')),
                        ('losses_1_3', models.IntegerField(default=0, verbose_name='Derrotas 1-3')),
                        ('losses_0_3', models.IntegerField(default=0, verbose_name='Derrotas 0-3')),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='competitions.league')),
                        ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='teams.team')),
                    ],
                    options={
                        'verbose_name': 'Clasificación',
                        'verbose_name_plural': 'Clasificaciones',
                        'db_table': 'videos_standing',
                        'ordering': ['position'],
                        'unique_together': {('league', 'team')},
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
