# Generated by Django 6.0.8 on 2026-09-19 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_migrate_league_category_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='category',
        ),
    ]
