# Generated by Django 6.0.8 on 2026-09-20 12:38
# Ajustada a mano para migrar League.season (CharField) -> FK a core.Season
# sin perder datos: renombra el campo, crea la FK, rellena con el histórico
# normalizado y elimina el campo string.

import django.db.models.deletion
from django.db import migrations, models

from videosvoley.core.models import normalize_season_name


def backfill_season_fk(apps, schema_editor):
    League = apps.get_model('competitions', 'League')
    Season = apps.get_model('core', 'Season')
    for league in League.objects.exclude(season_name__isnull=True).exclude(season_name=''):
        name = normalize_season_name(league.season_name)
        if not name:
            continue
        start_year = int(name.split('-')[0])
        season, _ = Season.objects.get_or_create(
            name=name,
            defaults={'start_year': start_year, 'end_year': start_year + 1},
        )
        league.season_id = season.pk
        league.save(update_fields=['season'])


def reverse_season_fk(apps, schema_editor):
    League = apps.get_model('competitions', 'League')
    for league in League.objects.exclude(season__isnull=True).select_related('season'):
        league.season_name = league.season.name
        league.save(update_fields=['season_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_remove_league_category'),
        ('core', '0007_season'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='league',
            unique_together=set(),
        ),
        migrations.RenameField(
            model_name='league',
            old_name='season',
            new_name='season_name',
        ),
        migrations.AddField(
            model_name='league',
            name='season',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='leagues',
                to='core.season',
                verbose_name='Temporada',
            ),
        ),
        migrations.RunPython(backfill_season_fk, reverse_season_fk),
        migrations.RemoveField(
            model_name='league',
            name='season_name',
        ),
    ]
