# Generated by Django 6.0.8 on 2026-09-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_alter_league_unique_together_alter_league_season'),
        ('teams', '0003_backfill_team_club'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['match_date'], name='match_date_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['league', 'match_date'], name='match_league_date_idx'),
        ),
    ]
