# Generated by Django 6.0.8 on 2026-09-27 13:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_match_match_date_idx_match_match_league_date_idx'),
        ('core', '0008_organization_default_home'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_share_links', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='competitions.match')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_share_links', to='core.organization')),
            ],
            options={
                'verbose_name': 'Enlace de partido',
                'verbose_name_plural': 'Enlaces de partido',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['match', '-created_at'], name='share_match_created_idx')],
            },
        ),
    ]
