# Generated by Django 6.0.8 on 2026-09-27 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_match_match_date_idx_match_match_league_date_idx'),
        ('rosters', '0006_person_organization'),
        ('teams', '0003_backfill_team_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='acta_data',
            field=models.JSONField(blank=True, help_text='JSON estructurado del acta federativa (convocados, alineaciones y sets)', null=True, verbose_name='Acta parseada'),
        ),
        migrations.CreateModel(
            name='MatchLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Dorsal')),
                ('name_acta', models.CharField(blank=True, max_length=200, verbose_name='Nombre en acta')),
                ('is_convocado', models.BooleanField(default=False, verbose_name='Convocado')),
                ('sets_played', models.PositiveSmallIntegerField(default=0, verbose_name='Sets jugados')),
                ('sets_started', models.PositiveSmallIntegerField(default=0, verbose_name='Sets como titular')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_lineups', to='competitions.match')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_lineups', to='rosters.person', verbose_name='Deportista')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_lineups', to='teams.team')),
            ],
            options={
                'verbose_name': 'Alineación de partido',
                'verbose_name_plural': 'Alineaciones de partido',
                'db_table': 'videos_matchlineup',
                'ordering': ['match', 'team', 'jersey_number'],
                'indexes': [models.Index(fields=['person', 'match'], name='lineup_person_match_idx'), models.Index(fields=['team', 'match'], name='lineup_team_match_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('jersey_number__isnull', False)), fields=('match', 'team', 'jersey_number'), name='unique_lineup_jersey_per_match')],
            },
        ),
    ]
