# Generated by Django 6.0.8 on 2026-09-27 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_match_match_date_idx_match_match_league_date_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('datetime', 'Fecha / Hora'), ('venue', 'Sede / Pabellón'), ('status', 'Estado'), ('score', 'Tanteo / Resultado'), ('other', 'Otro')], default='other', max_length=20)),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('is_last_minute', models.BooleanField(default=False, help_text='Indica si el cambio se detectó con menos de 7 días de antelación al partido')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='competitions.match')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_match_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modificación de Partido',
                'verbose_name_plural': 'Modificaciones de Partidos',
                'db_table': 'videos_matchchangelog',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['match', 'detected_at'], name='match_change_match_idx'), models.Index(fields=['is_last_minute', 'notified'], name='match_change_notif_idx')],
            },
        ),
    ]
