# Generated by Django 6.0.8 on 2026-09-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_match_acta_data_matchlineup'),
        ('competitions', '0007_matchchangelog'),
    ]

    operations = [
    ]
