# Generated by Django 6.0.8 on 2026-09-27 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_match_share_link'),
        ('competitions', '0008_merge_20260927_1534'),
    ]

    operations = [
    ]
