# Generated by Django 6.0.8 on 2026-09-27 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_merge_0007_match_share_link_0008_merge_20260927_1534'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchsharelink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_share_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='matchchangelog',
            index=models.Index(fields=['reviewed', '-detected_at'], name='match_change_review_idx'),
        ),
    ]
