# Generated by Django 6.0.8 on 2026-09-30 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_match_result_penalized_match_set_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre canónico del pabellón o instalación deportiva', max_length=200, unique=True, verbose_name='Nombre oficial')),
                ('short_name', models.CharField(blank=True, help_text='Nombre abreviado para listados compactos', max_length=100, verbose_name='Nombre corto')),
                ('address', models.CharField(blank=True, help_text='Dirección física completa (calle, número)', max_length=500, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Municipio')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Código postal')),
                ('google_maps_url', models.URLField(blank=True, help_text='Enlace corto o directo a la ubicación en Google Maps (ej. https://maps.app.goo.gl/...)', max_length=500, verbose_name='Enlace Google Maps')),
                ('aliases', models.TextField(blank=True, help_text='Variaciones de nombre separadas por coma o salto de línea usadas en federación (ej: Pav. Municipal Alaró, Pista 1, Pista 2)', verbose_name='Nombres alternativos / Alias')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pabellón / Sede',
                'verbose_name_plural': 'Pabellones / Sedes',
                'db_table': 'videos_venue',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='venue_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='competitions.venue', verbose_name='Pabellón'),
        ),
    ]
