# Generated by Django 6.0.8 on 2026-10-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_match_result_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se envió el recordatorio push 2h antes del partido para evitar duplicados.', null=True, verbose_name='Recordatorio 2h enviado el'),
        ),
    ]
