# Generated by Django 6.0.8 on 2026-10-01 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0016_match_reminder_sent_at'),
        ('core', '0009_organization_notify_match_changes'),
        ('rosters', '0007_remove_person_unique_person_identity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FederationCallUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título de la circular')),
                ('circular_date', models.DateField(blank=True, null=True, verbose_name='Fecha de circular')),
                ('source_url', models.CharField(help_text='Nombre del fichero PDF remoto (ej: 1785324870_3735.pdf)', max_length=255, unique=True, verbose_name='Archivo PDF / URL de origen')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='callups/pdfs/%Y/', verbose_name='Archivo PDF local')),
                ('pdf_sha256', models.CharField(blank=True, max_length=64, verbose_name='SHA256 del PDF')),
                ('modality', models.CharField(choices=[('beach', 'Vóley Playa'), ('indoor', 'Vóley Pista')], default='indoor', max_length=20, verbose_name='Modalidad')),
                ('category_name', models.CharField(blank=True, max_length=50, verbose_name='Categoría')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Mixto / No especificado')], default='X', max_length=10, verbose_name='Género')),
                ('callup_number', models.CharField(blank=True, max_length=50, verbose_name='Número de convocatoria')),
                ('raw_text', models.TextField(blank=True, verbose_name='Texto extraído del PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='callups', to='core.season', verbose_name='Temporada')),
            ],
            options={
                'verbose_name': 'Convocatoria Federativa',
                'verbose_name_plural': 'Convocatorias Federativas',
                'db_table': 'competitions_federation_callup',
                'ordering': ['-circular_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallUpPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_club', models.CharField(blank=True, max_length=150, verbose_name='Club en PDF')),
                ('raw_last_name', models.CharField(blank=True, max_length=150, verbose_name='Apellidos en PDF')),
                ('raw_first_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre en PDF')),
                ('raw_birth_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año nacimiento en PDF')),
                ('match_status', models.CharField(choices=[('confirmed', 'Confirmado'), ('suspected', 'Dudoso / Requiere Revisión'), ('rejected', 'Descartado'), ('unmatched', 'Sin Coincidencia (Otro Club)')], default='unmatched', max_length=20, verbose_name='Estado del cruce')),
                ('match_score', models.FloatField(default=0.0, verbose_name='Puntuación de coincidencia')),
                ('match_notes', models.CharField(blank=True, max_length=255, verbose_name='Notas del cruce')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Notificación enviada')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callup_players', to='core.organization', verbose_name='Organización / Tenant')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callups', to='rosters.person', verbose_name='Persona Vinculada')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('callup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='competitions.federationcallup', verbose_name='Convocatoria')),
            ],
            options={
                'verbose_name': 'Jugador Convocado',
                'verbose_name_plural': 'Jugadores Convocados',
                'db_table': 'competitions_callup_player',
                'ordering': ['callup', 'raw_last_name', 'raw_first_name'],
            },
        ),
    ]
