# Generated by Django 6.0.8 on 2026-10-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_federationcallup_callupplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callupplayer',
            name='match_status',
            field=models.CharField(choices=[('confirmed', 'Confirmado'), ('suspected', 'Dudoso / Requiere Revisión'), ('rejected', 'Descartado'), ('unmatched', 'Sin coincidencia')], default='unmatched', max_length=20, verbose_name='Estado del cruce'),
        ),
    ]
