# Generated by Django 6.0.8 on 2026-10-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_alter_callupplayer_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='federationcallup',
            name='callup_type',
            field=models.CharField(choices=[('selection', 'Selección Balear'), ('training', 'Tecnificación'), ('follow_up', 'Seguimiento federativo'), ('supervision', 'Supervisión')], default='selection', help_text='Selección Balear, tecnificación, seguimiento federativo o supervisión', max_length=20, verbose_name='Tipo de circular'),
        ),
    ]
