# Generated by Django 6.0.8 on 2026-10-03 16:44

from django.db import migrations


def backfill_acta_urls(apps, schema_editor):
    Match = apps.get_model('competitions', 'Match')
    matches = (
        Match.objects
        .exclude(acta_html='')
        .exclude(acta_html__isnull=True)
        .exclude(acta_html__startswith='http://')
        .exclude(acta_html__startswith='https://')
        .exclude(federation_id__isnull=True)
        .exclude(federation_id='')
    )
    for match in matches.iterator():
        cleaned_acta = match.acta_html.strip()
        fed_id = str(match.federation_id).strip()
        if cleaned_acta and fed_id:
            match.acta_html = f"https://voleibolib.federatio.com/actas/{fed_id}/{cleaned_acta}"
            match.save(update_fields=['acta_html'])


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0020_clean_venue_maps_urls_and_add_coordinates'),
    ]

    operations = [
        migrations.RunPython(backfill_acta_urls, migrations.RunPython.noop),
    ]
