# Generated by Django 6.0.8 on 2026-10-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0021_backfill_acta_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='photo_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se envió el push para animar a subir fotos del partido, para evitar duplicados.', null=True, verbose_name='Recordatorio de fotos enviado el'),
        ),
    ]
