# Generated by Django 6.0.8 on 2026-10-06 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0021_backfill_acta_urls'),
        ('core', '0014_backfill_santjosep_gradient_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federation_id', models.CharField(max_length=200, unique=True)),
                ('section', models.CharField(blank=True, max_length=200)),
                ('category_label', models.CharField(blank=True, max_length=200)),
                ('phase_label', models.CharField(blank=True, max_length=200)),
                ('matched_teams', models.JSONField(default=dict, help_text='{slug del tenant: [equipos que juegan]}')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Detectada del menú; vacía si es ambigua (asignar al aprobar)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('league', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate', to='competitions.league')),
                ('parent_league', models.ForeignKey(blank=True, help_text='Si es una fase de otra liga (Oro/Plata, copas). Sugerida por categoría; la federación no es consistente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='competitions.league')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='league_candidates', to='core.season')),
            ],
            options={
                'verbose_name': 'Liga candidata',
                'verbose_name_plural': 'Ligas candidatas',
                'ordering': ['-created_at'],
            },
        ),
    ]
