# Generated by Django 6.0.8 on 2026-10-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0022_match_photo_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='federation_comment',
            field=models.TextField(blank=True, help_text='Aviso de la federación (aplazamientos, cambios) tal cual viene del JSON', verbose_name='Comentario federativo'),
        ),
    ]
