# Generated by Django 6.0.8 on 2026-10-06 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0023_leaguecandidate'),
        ('competitions', '0023_match_federation_comment'),
    ]

    operations = [
    ]
