# Generated by Django 6.0.8 on 2026-10-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0024_merge_20261007_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguecandidate',
            name='is_historical',
            field=models.BooleanField(default=False, help_text='Detectada en una temporada pasada: al aprobar se crea como liga histórica inactiva.'),
        ),
    ]
