# Generated by Django 6.0.8 on 2026-10-07 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0024_merge_20261007_0056'),
        ('core', '0014_backfill_santjosep_gradient_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederationCircular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Competiciones'), (6, 'Comité de competición'), (8, 'Vóley playa'), (9, 'Formación'), (11, 'Normas y reglamentos'), (12, 'Árbitros'), (13, 'Documentos FVBIB'), (15, 'Transparencia')], verbose_name='Tipo')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('circular_date', models.DateField(blank=True, null=True, verbose_name='Fecha de circular')),
                ('file_name', models.CharField(blank=True, help_text='Vacío si la circular no tiene PDF adjunto.', max_length=255, verbose_name='Fichero PDF remoto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circulars', to='core.season', verbose_name='Temporada')),
            ],
            options={
                'verbose_name': 'Circular federativa',
                'verbose_name_plural': 'Circulares federativas',
                'ordering': ['-circular_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'title', 'circular_date'), name='unique_federation_circular')],
            },
        ),
    ]
