# Generated by Django 6.0.8 on 2026-10-07 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0025_federation_circular'),
        ('core', '0014_backfill_santjosep_gradient_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='federationcircular',
            name='rows_extracted_at',
            field=models.DateTimeField(blank=True, help_text='Solo en circulares disciplinarias: cuándo se leyó el PDF para extraer las filas de los tenants.', null=True, verbose_name='Filas extraídas'),
        ),
        migrations.CreateModel(
            name='FederationSanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveSmallIntegerField()),
                ('sanction_date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('text', models.TextField(verbose_name='Fila de la circular')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Categoría guardada cuyo nombre aparece en la fila, si la hay.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='federation_sanctions', to='core.category', verbose_name='Categoría')),
                ('circular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='competitions.federationcircular')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='federation_sanctions', to='core.organization', verbose_name='Organización / Tenant')),
            ],
            options={
                'verbose_name': 'Sanción federativa',
                'verbose_name_plural': 'Sanciones federativas',
                'ordering': ['-sanction_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('circular', 'organization', 'row_index'), name='unique_federation_sanction_row')],
            },
        ),
    ]
