# Generated by Django 6.0.8 on 2026-10-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0026_federation_sanction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederationNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federation_id', models.PositiveIntegerField(unique=True)),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('title', models.CharField(max_length=500, verbose_name='Titular')),
                ('kind', models.CharField(blank=True, help_text='Etiqueta de la federación (Generales, Arbitros…); la playa reciente llega como Generales.', max_length=50, verbose_name='Tipo')),
                ('image_name', models.CharField(blank=True, max_length=255, verbose_name='Imagen remota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Noticia federativa',
                'verbose_name_plural': 'Noticias federativas',
                'ordering': ['-published_at', '-federation_id'],
            },
        ),
    ]
