# Generated by Django 6.0.8 on 2026-10-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0027_federation_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='federationnews',
            name='club_name',
            field=models.CharField(blank=True, help_text='Solo en actividades de clubes (campus, eventos), tal como lo publica la federación.', max_length=255, verbose_name='Club'),
        ),
    ]
