# Generated by Django 6.0.8 on 2026-10-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0025_leaguecandidate_is_historical'),
        ('competitions', '0028_federation_news_club'),
    ]

    operations = [
    ]
