# Generated by Django 6.0.8 on 2026-10-08 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0029_merge_20261007_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stream_notified_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se envió la notificación push del directo para evitar duplicados.', null=True, verbose_name='Aviso de directo enviado el'),
        ),
        migrations.AddField(
            model_name='match',
            name='stream_url',
            field=models.URLField(blank=True, default='', help_text='Enlace de la emisión en directo (YouTube, Instagram, etc.). Solo http y https.', max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Enlace de retransmisión'),
        ),
    ]
