# Generated by Django 6.0.8 on 2026-10-07 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0029_merge_20261007_1612'),
        ('content', '0010_imagefavorite'),
        ('core', '0014_backfill_santjosep_gradient_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_format', models.CharField(choices=[('story', 'Story 9:16'), ('square', 'Cuadrado 1:1')], default='story', max_length=10, verbose_name='Formato')),
                ('layout', models.JSONField(blank=True, default=dict, verbose_name='Composición')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_compositions', to='content.image', verbose_name='Foto')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_compositions', to='competitions.match', verbose_name='Partido')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_compositions', to='core.organization', verbose_name='Organización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_compositions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Composición de story',
                'verbose_name_plural': 'Composiciones de story',
                'ordering': ['-updated'],
            },
        ),
    ]
