# Generated by Django 6.0.8 on 2026-10-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0030_storycomposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='modality',
            field=models.CharField(choices=[('beach', 'Vóley Playa'), ('indoor', 'Vóley Pista')], db_index=True, default='indoor', help_text='Modalidad de la competición: pista o playa', max_length=20, verbose_name='Modalidad'),
        ),
        migrations.AddField(
            model_name='leaguecandidate',
            name='modality',
            field=models.CharField(choices=[('beach', 'Vóley Playa'), ('indoor', 'Vóley Pista')], db_index=True, default='indoor', max_length=20, verbose_name='Modalidad'),
        ),
    ]
