# Generated by Django 6.0.8 on 2026-10-08 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_reviewed_to_per_org(apps, schema_editor):
    """Traslada reviewed=True a MatchChangeLogReview cuando hay una sola org clara.

    Si el partido involucra 0 o >1 organizaciones con club participante, se
    deja sin migrar (ambiguo): el club deberá marcar de nuevo (#201).
    """
    MatchChangeLog = apps.get_model('competitions', 'MatchChangeLog')
    MatchChangeLogReview = apps.get_model('competitions', 'MatchChangeLogReview')
    Organization = apps.get_model('core', 'Organization')

    reviewed_logs = (
        MatchChangeLog.objects.filter(reviewed=True)
        .select_related('match__home_team', 'match__away_team')
        .iterator()
    )
    to_create = []
    for log in reviewed_logs:
        club_ids = {
            cid for cid in (
                getattr(log.match.home_team, 'club_id', None) if log.match.home_team_id else None,
                getattr(log.match.away_team, 'club_id', None) if log.match.away_team_id else None,
            ) if cid
        }
        if not club_ids:
            continue
        orgs = list(Organization.objects.filter(club_id__in=club_ids))
        if len(orgs) != 1:
            continue
        to_create.append(MatchChangeLogReview(
            change_log_id=log.pk,
            organization_id=orgs[0].pk,
            reviewed_by_id=log.reviewed_by_id,
            reviewed_at=log.reviewed_at,
        ))
    if to_create:
        MatchChangeLogReview.objects.bulk_create(to_create, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0031_match_stream_notified_at_match_stream_url'),
        ('core', '0014_backfill_santjosep_gradient_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchChangeLogReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Revisión de modificación de partido',
                'verbose_name_plural': 'Revisiones de modificaciones de partidos',
            },
        ),
        migrations.RemoveIndex(
            model_name='matchchangelog',
            name='match_change_review_idx',
        ),
        migrations.AddField(
            model_name='matchchangelogreview',
            name='change_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='competitions.matchchangelog'),
        ),
        migrations.AddField(
            model_name='matchchangelogreview',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_change_reviews', to='core.organization'),
        ),
        migrations.AddField(
            model_name='matchchangelogreview',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_change_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(migrate_reviewed_to_per_org, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='matchchangelog',
            name='reviewed',
        ),
        migrations.RemoveField(
            model_name='matchchangelog',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='matchchangelog',
            name='reviewed_by',
        ),
        migrations.AddIndex(
            model_name='matchchangelogreview',
            index=models.Index(fields=['organization', '-reviewed_at'], name='match_change_review_org_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchchangelogreview',
            constraint=models.UniqueConstraint(fields=('change_log', 'organization'), name='unique_matchchangelog_review_per_org'),
        ),
    ]
