# Generated by Django 6.0.8 on 2026-10-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0031_league_modality_leaguecandidate_modality'),
        ('competitions', '0032_matchchangelog_review_per_org'),
    ]

    operations = [
    ]
