# Generated by Django 6.0.8 on 2026-10-09 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0033_merge_20261008_1333'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchActaPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=500, verbose_name='URL origen')),
                ('status', models.CharField(choices=[('pending_download', 'Pendiente de descarga'), ('pending_review', 'Pendiente de revisión'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('unreadable', 'Ilegible'), ('expired', 'Caducada')], default='pending_download', max_length=20, verbose_name='Estado')),
                ('image', models.ImageField(blank=True, null=True, upload_to='actas_photos/%Y/%m/', verbose_name='Foto del acta')),
                ('extracted_data', models.JSONField(blank=True, null=True, verbose_name='Datos extraídos')),
                ('extraction_meta', models.JSONField(blank=True, default=dict, verbose_name='Metadatos de extracción')),
                ('validation_errors', models.JSONField(blank=True, default=list, verbose_name='Errores de validación')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revisado el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acta_photo', to='competitions.match', verbose_name='Partido')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_acta_photos', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Foto de acta manual',
                'verbose_name_plural': 'Fotos de actas manuales',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='acta_photo_status_idx')],
            },
        ),
    ]
