# Generated by Django 6.0.8 on 2026-10-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0034_matchactaphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchactaphoto',
            name='status',
            field=models.CharField(choices=[('pending_download', 'Pendiente de descarga'), ('downloaded', 'Descargada'), ('pending_read', 'Pendiente de lectura'), ('pending_review', 'Pendiente de revisión'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('unreadable', 'Ilegible'), ('expired', 'Caducada')], default='pending_download', max_length=20, verbose_name='Estado'),
        ),
    ]
