# Generated by Django 6.0.8 on 2026-09-19 11:46

import django.core.validators
import django.db.models.deletion
import videosvoley.content.models.content
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_organization_club'),
        ('videos', '0037_move_rosters_to_app'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Video',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=200)),
                        ('youtube_url', models.URLField()),
                        ('description', models.TextField(blank=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.category')),
                        ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                        ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='videos.match')),
                        ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='core.organization', verbose_name='Organización')),
                    ],
                    options={
                        'db_table': 'videos_video',
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='Comment',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('content', models.TextField(max_length=500)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                        ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.video')),
                    ],
                    options={
                        'db_table': 'videos_comment',
                        'ordering': ['created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='Image',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('image', models.ImageField(help_text='Formatos permitidos: JPG, PNG, WebP, HEIC. Tamaño máximo: 10MB', upload_to=videosvoley.content.models.content.image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'heic', 'heif'])])),
                        ('title', models.CharField(help_text='Título descriptivo de la imagen', max_length=200)),
                        ('description', models.TextField(blank=True, help_text='Descripción opcional')),
                        ('original_format', models.CharField(blank=True, help_text='Formato original del archivo (ej: heic, jpg)', max_length=10)),
                        ('was_converted', models.BooleanField(default=False, help_text='Indica si la imagen fue convertida desde otro formato')),
                        ('image_type', models.CharField(choices=[('match', 'Partido'), ('celebration', 'Celebración'), ('training', 'Entrenamiento'), ('team_photo', 'Foto de Equipo'), ('facilities', 'Instalaciones'), ('other', 'Otro')], default='other', help_text='Tipo de imagen', max_length=20)),
                        ('tags', models.CharField(blank=True, help_text='Etiquetas separadas por comas (ej: gol, victoria, senior)', max_length=500)),
                        ('auto_tags', models.JSONField(blank=True, default=list, help_text='Etiquetas detectadas automáticamente por Vision API')),
                        ('album_group_id', models.UUIDField(blank=True, help_text='ID de grupo para agrupar imágenes en un álbum sin partido vinculado', null=True)),
                        ('album_name', models.CharField(blank=True, help_text='Nombre del álbum cuando las imágenes están agrupadas sin partido', max_length=200)),
                        ('year', models.IntegerField(help_text='Año de la temporada')),
                        ('upload_date', models.DateTimeField(auto_now_add=True)),
                        ('status', models.CharField(choices=[('pending', 'Pendiente de Moderación'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', help_text='Estado de moderación', max_length=20)),
                        ('moderation_date', models.DateTimeField(blank=True, null=True)),
                        ('moderation_notes', models.TextField(blank=True, help_text='Notas internas de moderación')),
                        ('vision_api_checked', models.BooleanField(default=False)),
                        ('vision_api_safe', models.BooleanField(default=True)),
                        ('vision_api_details', models.JSONField(blank=True, default=dict)),
                        ('categories', models.ManyToManyField(blank=True, db_table='videos_image_categories', help_text='Categorías asociadas a la imagen. Se asigna automáticamente desde el partido o manualmente', related_name='images', to='videos.category')),
                        ('match', models.ForeignKey(blank=True, help_text='Partido al que pertenece la imagen (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='videos.match')),
                        ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_images', to=settings.AUTH_USER_MODEL)),
                        ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='core.organization', verbose_name='Organización')),
                        ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Imagen',
                        'verbose_name_plural': 'Imágenes',
                        'db_table': 'videos_image',
                        'ordering': ['-upload_date'],
                        'indexes': [
                            models.Index(fields=['status'], name='videos_imag_status_4a5f9f_idx'),
                            models.Index(fields=['match'], name='videos_imag_match_i_ad5ca3_idx'),
                            models.Index(fields=['album_group_id'], name='videos_imag_album_g_2185c3_idx'),
                            models.Index(fields=['year'], name='videos_imag_year_e48770_idx'),
                            models.Index(fields=['upload_date'], name='videos_imag_upload__b5adc6_idx'),
                            models.Index(fields=['image_type'], name='videos_imag_image_t_6f0bde_idx'),
                        ],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
