# Generated by Django 6.0.8 on 2026-09-19 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='match',
            field=models.ForeignKey(blank=True, help_text='Partido al que pertenece la imagen (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='competitions.match'),
        ),
        migrations.AlterField(
            model_name='video',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='competitions.match'),
        ),
    ]
