# Generated by Django 6.0.8 on 2026-09-19 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_image_match_alter_video_match'),
        ('core', '0006_move_category_to_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='categories',
            field=models.ManyToManyField(blank=True, db_table='videos_image_categories', help_text='Categorías asociadas a la imagen. Se asigna automáticamente desde el partido o manualmente', related_name='images', to='core.category'),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
