# Generated by Django 6.0.8 on 2026-09-25 16:26

from django.db import migrations


def _sanitize_file_in_storage(storage, file_name):
    if not file_name or not storage.exists(file_name):
        return

    from io import BytesIO
    from PIL import Image, ImageOps
    from django.core.files.base import ContentFile

    try:
        from pillow_heif import register_heif_opener
        register_heif_opener()
    except ImportError:
        pass

    try:
        with storage.open(file_name, 'rb') as f:
            content = f.read()
        if not content:
            return

        with Image.open(BytesIO(content)) as img:
            has_exif = bool(img.info.get('exif') or (hasattr(img, '_getexif') and img._getexif()))
            exceeds_size = max(img.size) > 2560
            is_jpeg = img.format == 'JPEG'

            # Si ya es JPEG optimizado, sin EXIF ni coordenadas GPS y dentro de límites, saltar
            if not has_exif and not exceeds_size and is_jpeg:
                return

            # Corregir orientación antes de purgar EXIF
            img = ImageOps.exif_transpose(img) or img

            # Redimensionar si excede 2560px
            if max(img.size) > 2560:
                img.thumbnail((2560, 2560), Image.Resampling.LANCZOS)

            # Convertir a RGB
            if img.mode in ('RGBA', 'LA', 'P'):
                bg = Image.new('RGB', img.size, (255, 255, 255))
                if img.mode in ('RGBA', 'LA'):
                    bg.paste(img, mask=img.split()[-1])
                else:
                    rgba = img.convert('RGBA')
                    bg.paste(rgba, mask=rgba.split()[-1])
                img = bg
            elif img.mode != 'RGB':
                img = img.convert('RGB')

            out = BytesIO()
            img.save(out, format='JPEG', quality=85, optimize=True, progressive=True)
            sanitized_bytes = out.getvalue()

        # Sobrescribir en almacenamiento sin metadatos EXIF
        storage.delete(file_name)
        storage.save(file_name, ContentFile(sanitized_bytes))
    except Exception:
        # Si un archivo está corrupto o no es imagen válida, continuar sin romper la migración
        pass


def purge_exif_gps_metadata(apps, schema_editor):
    from django.core.files.storage import default_storage

    Image = apps.get_model('content', 'Image')
    Person = apps.get_model('rosters', 'Person')
    User = apps.get_model('users', 'User')

    for img_obj in Image.objects.all().iterator(chunk_size=100):
        if img_obj.image and img_obj.image.name:
            _sanitize_file_in_storage(default_storage, img_obj.image.name)

    for person_obj in Person.objects.exclude(photo='').exclude(photo__isnull=True).iterator(chunk_size=100):
        if person_obj.photo and person_obj.photo.name:
            _sanitize_file_in_storage(default_storage, person_obj.photo.name)

    for user_obj in User.objects.exclude(avatar='').exclude(avatar__isnull=True).iterator(chunk_size=100):
        if user_obj.avatar and user_obj.avatar.name:
            _sanitize_file_in_storage(default_storage, user_obj.avatar.name)


def reverse_purge(apps, schema_editor):
    # La eliminación de metadatos sensibles es irreversible
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_image_videos_imag_year_e48770_idx_and_more'),
        ('rosters', '0005_remove_playerrole_unique_active_player_role_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(purge_exif_gps_metadata, reverse_purge),
    ]
