# Generated by Django 6.0.8 on 2026-09-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_image_videos_imag_year_e48770_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail_large',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='image_thumbnails/', verbose_name='Miniatura 1600px WebP'),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_large_avif',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='image_thumbnails/', verbose_name='Miniatura 1600px AVIF'),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_small',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='image_thumbnails/', verbose_name='Miniatura 400px WebP'),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_small_avif',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='image_thumbnails/', verbose_name='Miniatura 400px AVIF'),
        ),
    ]
