# Generated by Django 6.0.8 on 2026-09-25 16:26

import logging
import os
from pathlib import Path

from django.db import migrations

logger = logging.getLogger(__name__)


def _overwrite_storage_file(storage, file_name, sanitized_bytes):
    """Escribe el contenido de forma atómica cuando el storage lo permite."""
    from django.core.files.base import ContentFile

    if hasattr(storage, 'path'):
        full = Path(storage.path(file_name))
        tmp = full.with_suffix(full.suffix + '.sanitizing')
        tmp.write_bytes(sanitized_bytes)
        os.replace(tmp, full)
        return

    tmp_name = f'{file_name}.sanitizing'
    if storage.exists(tmp_name):
        storage.delete(tmp_name)
    saved_tmp = storage.save(tmp_name, ContentFile(sanitized_bytes))
    storage.delete(file_name)
    # Re-guardar con el nombre original; si falla, el .sanitizing queda como rastro.
    storage.save(file_name, ContentFile(storage.open(saved_tmp).read()))
    storage.delete(saved_tmp)


def _sanitize_file_in_storage(storage, file_name):
    if not file_name or not storage.exists(file_name):
        return

    from io import BytesIO
    from PIL import Image, ImageOps

    try:
        from pillow_heif import register_heif_opener
        register_heif_opener()
    except ImportError:
        pass

    try:
        with storage.open(file_name, 'rb') as f:
            content = f.read()
        if not content:
            return

        with Image.open(BytesIO(content)) as img:
            has_exif = bool(img.info.get('exif') or (hasattr(img, '_getexif') and img._getexif()))
            exceeds_size = max(img.size) > 2560
            fmt = (img.format or '').upper()
            if fmt == 'JPG':
                fmt = 'JPEG'

            # Sin EXIF ni exceso de tamaño: no tocar (cualquier formato).
            if not has_exif and not exceeds_size:
                return

            # Solo reescribimos formatos que podemos preservar con la misma extensión.
            if fmt not in ('JPEG', 'PNG', 'WEBP'):
                return

            img = ImageOps.exif_transpose(img) or img

            if max(img.size) > 2560:
                img.thumbnail((2560, 2560), Image.Resampling.LANCZOS)

            out = BytesIO()
            if fmt == 'JPEG':
                if img.mode in ('RGBA', 'LA', 'P'):
                    bg = Image.new('RGB', img.size, (255, 255, 255))
                    if img.mode in ('RGBA', 'LA'):
                        bg.paste(img, mask=img.split()[-1])
                    else:
                        rgba = img.convert('RGBA')
                        bg.paste(rgba, mask=rgba.split()[-1])
                    img = bg
                elif img.mode != 'RGB':
                    img = img.convert('RGB')
                img.save(out, format='JPEG', quality=85, optimize=True, progressive=True)
            elif fmt == 'PNG':
                if img.mode == 'P':
                    img = img.convert('RGBA')
                img.save(out, format='PNG', optimize=True)
            else:  # WEBP
                img.save(out, format='WEBP', quality=85)

            sanitized_bytes = out.getvalue()

        _overwrite_storage_file(storage, file_name, sanitized_bytes)
    except OSError:
        # Fallo de storage: no silenciar — la migración debe fallar para reintentar.
        logger.exception('Fallo de storage purgando EXIF en %s', file_name)
        raise
    except Exception:
        # Archivo corrupto o no imagen: continuar sin romper la migración.
        logger.warning('No se pudo purgar EXIF de %s; se omite', file_name, exc_info=True)


def purge_exif_gps_metadata(apps, schema_editor):
    from django.core.files.storage import default_storage

    Image = apps.get_model('content', 'Image')
    Person = apps.get_model('rosters', 'Person')
    User = apps.get_model('users', 'User')

    for img_obj in Image.objects.all().iterator(chunk_size=100):
        if img_obj.image and img_obj.image.name:
            _sanitize_file_in_storage(default_storage, img_obj.image.name)

    for person_obj in Person.objects.exclude(photo='').exclude(photo__isnull=True).iterator(chunk_size=100):
        if person_obj.photo and person_obj.photo.name:
            _sanitize_file_in_storage(default_storage, person_obj.photo.name)

    for user_obj in User.objects.exclude(avatar='').exclude(avatar__isnull=True).iterator(chunk_size=100):
        if user_obj.avatar and user_obj.avatar.name:
            _sanitize_file_in_storage(default_storage, user_obj.avatar.name)


def reverse_purge(apps, schema_editor):
    # La eliminación de metadatos sensibles es irreversible
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_image_videos_imag_year_e48770_idx_and_more'),
        ('rosters', '0005_remove_playerrole_unique_active_player_role_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(purge_exif_gps_metadata, reverse_purge),
    ]
