# Generated by Django 6.0.8 on 2026-09-26 07:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_match_match_date_idx_match_match_league_date_idx'),
        ('content', '0004_remove_image_videos_imag_year_e48770_idx_and_more'),
        ('core', '0008_organization_default_home'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['organization', 'status', '-upload_date'], name='img_org_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['organization', 'match', 'status'], name='img_org_match_status_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['organization', 'album_group_id', 'status'], name='img_org_album_status_idx'),
        ),
    ]
