# Generated by Django 6.0.8 on 2026-09-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Depende de las dos hojas 0005 de develop para dejar un único leaf.
        ('content', '0005_image_img_org_status_date_idx_and_more'),
        ('content', '0005_purge_exif_gps_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail_large',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='image_thumbnails/', verbose_name='Miniatura 1600px WebP'),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_large_avif',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='image_thumbnails/', verbose_name='Miniatura 1600px AVIF'),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_small',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='image_thumbnails/', verbose_name='Miniatura 400px WebP'),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_small_avif',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='image_thumbnails/', verbose_name='Miniatura 400px AVIF'),
        ),
    ]
