# Generated by Django 6.0.8 on 2026-09-27 13:01

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_match_match_date_idx_match_match_league_date_idx'),
        ('content', '0006_image_thumbnail_large_image_thumbnail_large_avif_and_more'),
        ('core', '0008_organization_default_home'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='set_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número de set al que pertenece la imagen (opcional, solo si hay partido)', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Set'),
        ),
        migrations.AddField(
            model_name='video',
            name='set_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número de set al que pertenece (opcional, solo para vídeos de partido)', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Set'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['match', 'set_number'], name='img_match_set_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['match', 'set_number'], name='video_match_set_idx'),
        ),
    ]
