# Generated by Django 6.0.8 on 2026-10-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_add_set_number'),
        ('rosters', '0010_person_global_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='persons',
            field=models.ManyToManyField(blank=True, db_table='videos_image_persons', help_text='Personas que aparecen en la imagen', related_name='tagged_images', to='rosters.person', verbose_name='Deportistas etiquetados'),
        ),
    ]
