# Generated by Django 6.0.8 on 2026-10-06 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_image_persons'),
        ('core', '0014_backfill_santjosep_gradient_color'),
        ('rosters', '0010_person_global_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRemovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=200, verbose_name='Título de la imagen')),
                ('reason', models.TextField(blank=True, help_text='Motivo opcional de la solicitud', max_length=500, verbose_name='Motivo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('removed', 'Foto eliminada'), ('dismissed', 'Descartada')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelta')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removal_requests', to='content.image', verbose_name='Imagen')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image_removal_requests', to='core.organization', verbose_name='Organización')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_removal_requests', to='rosters.person', verbose_name='Deportista')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_removal_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitada por')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_image_removal_requests', to=settings.AUTH_USER_MODEL, verbose_name='Resuelta por')),
            ],
            options={
                'verbose_name': 'Solicitud de retirada de imagen',
                'verbose_name_plural': 'Solicitudes de retirada de imágenes',
                'db_table': 'videos_image_removal_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status', '-created_at'], name='img_rm_org_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('image',), name='unique_pending_image_removal')],
            },
        ),
    ]
