# Generated by Django 6.0.8 on 2026-10-06 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_imageremovalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='content.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'videos_image_favorite',
                'indexes': [models.Index(fields=['image'], name='videos_imag_image_i_12952a_idx'), models.Index(fields=['user', '-created_at'], name='fav_user_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'image'), name='unique_image_favorite_per_user')],
            },
        ),
    ]
