# Generated by Django 6.0.8 on 2026-09-14 20:27

import django.db.models.deletion
from django.db import migrations, models

# federation_id del Club en voleibolib → slug de Organization
_ORG_CLUB_FEDERATION_IDS = {
    'santjosep': '20',   # CLUB ESPORTIU SANT JOSEP OBRER
    'soller': '29',      # CLUB VOLEIBOL SÓLLER
}


def link_organizations_to_clubs(apps, schema_editor):
    Organization = apps.get_model('core', 'Organization')
    Club = apps.get_model('videos', 'Club')

    for slug, federation_id in _ORG_CLUB_FEDERATION_IDS.items():
        try:
            org = Organization.objects.get(slug=slug)
        except Organization.DoesNotExist:
            continue
        club = Club.objects.filter(federation_id=federation_id).first()
        if club:
            org.club_id = club.id
            org.save(update_fields=['club_id'])


def unlink_organizations_from_clubs(apps, schema_editor):
    Organization = apps.get_model('core', 'Organization')
    Organization.objects.filter(slug__in=_ORG_CLUB_FEDERATION_IDS).update(club=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organization_instagram_url'),
        ('videos', '0035_disable_friendly_scraping_endpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='club',
            field=models.ForeignKey(blank=True, help_text='Club federativo vinculado (opcional; null p.ej. para selecciones)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='videos.club'),
        ),
        migrations.RunPython(link_organizations_to_clubs, unlink_organizations_from_clubs),
    ]
