# Generated by Django 6.0.8 on 2026-09-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_move_category_to_core'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre canónico, ej: 2025-26', max_length=20, unique=True)),
                ('start_year', models.IntegerField(help_text='Año de inicio, ej: 2025')),
                ('end_year', models.IntegerField(help_text='Año de fin, ej: 2026')),
                ('is_current', models.BooleanField(default=False, help_text='Temporada activa (solo puede haber una)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
                'db_table': 'videos_season',
                'ordering': ['-start_year'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='unique_current_season')],
            },
        ),
    ]
