# Generated by Django 6.0.8 on 2026-09-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_home',
            field=models.CharField(choices=[('videos', 'Vídeos'), ('images', 'Imágenes'), ('competitions', 'Ligas y partidos')], default='videos', help_text='Sección a la que redirige la raíz del tenant.', max_length=20),
        ),
    ]
