# Generated by Django 6.0.8 on 2026-09-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_organization_default_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='notify_match_changes',
            field=models.BooleanField(default=True, help_text='Recibir avisos de cambios federativos de los partidos de sus equipos'),
        ),
    ]
