# Generated by Django 6.0.8 on 2026-10-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_organization_notify_match_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Sin especificar'), ('male', 'Masculino'), ('female', 'Femenino'), ('mixed', 'Mixto')], db_index=True, default='', help_text='Vacío si la categoría es genérica (ej. "Senior").', max_length=10, verbose_name='Género / Rama'),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_female_branch',
            field=models.BooleanField(default=False, help_text='Recibir avisos de partidos femeninos.', verbose_name='Rama femenina activa'),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_male_branch',
            field=models.BooleanField(default=True, help_text='Recibir avisos de partidos masculinos.', verbose_name='Rama masculina activa'),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_mixed_branch',
            field=models.BooleanField(default=False, help_text='Recibir avisos de partidos mixtos.', verbose_name='Rama mixta activa'),
        ),
    ]
