# Generated by Django 6.0.8 on 2026-10-01 21:35

from django.db import migrations


def _infer_gender(name):
    if not name:
        return ''
    lowered = name.lower()
    if 'femen' in lowered:
        return 'female'
    if 'mascul' in lowered:
        return 'male'
    if 'mixt' in lowered:
        return 'mixed'
    return ''


def backfill_category_gender(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    to_update = []
    for category in Category.objects.all():
        gender = _infer_gender(category.name)
        if gender and category.gender != gender:
            category.gender = gender
            to_update.append(category)
    if to_update:
        Category.objects.bulk_update(to_update, ['gender'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_category_gender_organization_has_female_branch_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_category_gender, migrations.RunPython.noop),
    ]
