# Generated by Django 6.0.8 on 2026-10-01 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_legacy_periodic_tasks'),
        ('core', '0011_backfill_category_gender'),
    ]

    operations = [
    ]
