# Generated by Django 6.0.8 on 2026-10-02 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20261002_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='gradient_color',
            field=models.CharField(blank=True, help_text='Color final del degradado de la cabecera del perfil. Vacío: usa el color secundario.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Introduce un color hexadecimal válido (ej: #9B7FBF)')]),
        ),
    ]
