# Generated by Django 6.0.8 on 2026-10-02 14:36

from django.db import migrations


def set_santjosep_gradient(apps, schema_editor):
    # Sant Josep mantiene su identidad histórica morado→amarillo (#297).
    apps.get_model('core', 'Organization').objects.filter(slug='santjosep', gradient_color='').update(
        gradient_color='#F4D47C'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_organization_gradient_color'),
    ]

    operations = [
        migrations.RunPython(set_santjosep_gradient, migrations.RunPython.noop),
    ]
