# Generated by Django 5.2.7 on 2025-10-04 11:08

from django.db import migrations


def create_video_managers_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='VideoManagers')


def reverse_create_video_managers_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='VideoManagers').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_video_managers_group, reverse_create_video_managers_group),
    ]