# Generated by Django 5.2.7 on 2025-10-04 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_create_video_managers_group'),
    ]

    operations = [
    ]
