# Generated by Django 5.2.7 on 2025-10-05 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_category_video_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('federation_id', models.CharField(max_length=50, unique=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('federation_id', models.CharField(max_length=50, unique=True)),
                ('competition_type', models.CharField(choices=[('regular', 'Liga Regular'), ('playoff', 'Playoff'), ('cup', 'Copa'), ('friendly', 'Amistoso')], default='regular', max_length=20)),
                ('season', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_url', models.URLField(default='https://www.voleibolib.net')),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligas',
                'ordering': ['-created_at'],
                'unique_together': {('federation_id', 'season')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('round_number', models.IntegerField(default=1)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('in_progress', 'En Progreso'), ('finished', 'Finalizado'), ('postponed', 'Aplazado'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20)),
                ('federation_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='videos.league')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='videos.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='videos.team')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['match_date'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_type', models.CharField(choices=[('standings', 'Clasificación'), ('results', 'Resultados'), ('calendar', 'Calendario')], max_length=20)),
                ('url_pattern', models.CharField(help_text='Usar {league_id}, {round}, etc. para parámetros dinámicos', max_length=500)),
                ('parser_type', models.CharField(choices=[('table_standings', 'Tabla de Clasificación'), ('match_results', 'Resultados de Partidos'), ('match_calendar', 'Calendario de Partidos')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_params', models.JSONField(blank=True, default=dict, help_text='Parámetros adicionales como JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='videos.league')),
            ],
            options={
                'verbose_name': 'Endpoint de Scraping',
                'verbose_name_plural': 'Endpoints de Scraping',
                'unique_together': {('league', 'endpoint_type')},
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('played', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('sets_for', models.IntegerField(default=0)),
                ('sets_against', models.IntegerField(default=0)),
                ('points_for', models.IntegerField(default=0)),
                ('points_against', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('wins_3_0', models.IntegerField(default=0, verbose_name='Victorias 3-0')),
                ('wins_3_1', models.IntegerField(default=0, verbose_name='Victorias 3-1')),
                ('wins_3_2', models.IntegerField(default=0, verbose_name='Victorias 3-2')),
                ('losses_2_3', models.IntegerField(default=0, verbose_name='Derrotas 2-3')),
                ('losses_1_3', models.IntegerField(default=0, verbose_name='Derrotas 1-3')),
                ('losses_0_3', models.IntegerField(default=0, verbose_name='Derrotas 0-3')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='videos.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='videos.team')),
            ],
            options={
                'verbose_name': 'Clasificación',
                'verbose_name_plural': 'Clasificaciones',
                'ordering': ['position'],
                'unique_together': {('league', 'team')},
            },
        ),
    ]
