# Generated by Django 5.2.7 on 2025-10-05 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_team_league_match_scrapingendpoint_standing'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='videos.match'),
        ),
    ]
