# Generated by Django 5.2.7 on 2025-10-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_video_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='federation_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='federation_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='federation_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
