# Generated by Django 5.2.7 on 2025-10-05 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_league_federation_id_alter_match_federation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues', to='videos.category'),
        ),
    ]
