# Generated by Django 5.2.7 on 2025-10-05 21:42

import django.core.validators
import django.db.models.deletion
import videosvoley.videos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_team_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Formatos permitidos: JPG, PNG, WebP. Tamaño máximo: 10MB', upload_to=videosvoley.videos.models.image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('title', models.CharField(help_text='Título descriptivo de la imagen', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción opcional')),
                ('year', models.IntegerField(help_text='Año de la temporada')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de Moderación'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', help_text='Estado de moderación', max_length=20)),
                ('moderation_date', models.DateTimeField(blank=True, null=True)),
                ('moderation_notes', models.TextField(blank=True, help_text='Notas internas de moderación')),
                ('vision_api_checked', models.BooleanField(default=False)),
                ('vision_api_safe', models.BooleanField(default=True)),
                ('vision_api_details', models.JSONField(blank=True, default=dict)),
                ('category', models.ForeignKey(blank=True, help_text='Se asigna automáticamente desde el partido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='videos.category')),
                ('match', models.ForeignKey(help_text='Partido al que pertenece la imagen', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='videos.match')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_images', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['status'], name='videos_imag_status_4a5f9f_idx'), models.Index(fields=['match'], name='videos_imag_match_i_ad5ca3_idx'), models.Index(fields=['category'], name='videos_imag_categor_7bbc73_idx'), models.Index(fields=['year'], name='videos_imag_year_e48770_idx'), models.Index(fields=['upload_date'], name='videos_imag_upload__b5adc6_idx')],
            },
        ),
    ]
