# Generated by Django 5.2.7 on 2025-10-05 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='auto_tags',
            field=models.JSONField(blank=True, default=list, help_text='Etiquetas detectadas automáticamente por Vision API'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_type',
            field=models.CharField(choices=[('match', 'Partido'), ('celebration', 'Celebración'), ('training', 'Entrenamiento'), ('team_photo', 'Foto de Equipo'), ('facilities', 'Instalaciones'), ('other', 'Otro')], default='other', help_text='Tipo de imagen', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.CharField(blank=True, help_text='Etiquetas separadas por comas (ej: gol, victoria, senior)', max_length=500),
        ),
        migrations.AlterField(
            model_name='image',
            name='match',
            field=models.ForeignKey(blank=True, help_text='Partido al que pertenece la imagen (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='videos.match'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['image_type'], name='videos_imag_image_t_6f0bde_idx'),
        ),
    ]
