# Generated by Django 5.2.7 on 2025-10-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_image_auto_tags_image_image_type_image_tags_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='image',
            name='videos_imag_categor_7bbc73_idx',
        ),
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.AddField(
            model_name='image',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categorías asociadas a la imagen. Se asigna automáticamente desde el partido o manualmente', related_name='images', to='videos.category'),
        ),
    ]
