# Generated by Django 5.2.7 on 2025-10-11 08:47

from django.db import migrations


def ensure_team_categories(apps, schema_editor):
    """Asegura que todos los equipos tengan categoría asignada"""
    Team = apps.get_model('videos', 'Team')
    Match = apps.get_model('videos', 'Match')
    
    # Buscar equipos sin categoría
    teams_without_category = Team.objects.filter(category__isnull=True)
    
    for team in teams_without_category:
        # Intentar obtener categoría desde la liga de algún partido
        # Buscar en partidos como local
        home_match = Match.objects.filter(home_team=team, league__category__isnull=False).first()
        if home_match and home_match.league and home_match.league.category:
            team.category = home_match.league.category
            team.save()
            continue
            
        # Buscar en partidos como visitante
        away_match = Match.objects.filter(away_team=team, league__category__isnull=False).first()
        if away_match and away_match.league and away_match.league.category:
            team.category = away_match.league.category
            team.save()
            continue
            
        # Si no se encontró categoría, marcar para revisión manual
        print(f"ADVERTENCIA: No se pudo asignar categoría automáticamente al equipo: {team.name}")


def reverse_ensure_team_categories(apps, schema_editor):
    """Operación reversible vacía"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0017_add_friendly_match_support'),
    ]

    operations = [
        migrations.RunPython(ensure_team_categories, reverse_ensure_team_categories),
    ]
