# Generated by Django 5.2.7 on 2025-10-11 23:10

from django.db import migrations


def migrate_players_and_staff_to_person_roles(apps, schema_editor):
    """
    Migra todos los datos de Player y Staff a la nueva estructura Person-Role.
    Detecta personas duplicadas y las consolida en una sola Person.
    """
    # Obtener los modelos
    Player = apps.get_model('videos', 'Player')
    Staff = apps.get_model('videos', 'Staff')
    Person = apps.get_model('videos', 'Person')
    PlayerRole = apps.get_model('videos', 'PlayerRole')
    StaffRole = apps.get_model('videos', 'StaffRole')
    
    # Diccionario para detectar personas duplicadas
    # Clave: (first_name, last_name, birth_date), Valor: Person instance
    people_map = {}
    
    print("🔄 Iniciando migración de datos de Player y Staff a Person-Role...")
    
    # PASO 1: Migrar Players
    players = Player.objects.all()
    print(f"📊 Migrando {players.count()} jugadores...")
    
    for player in players:
        # Crear clave única para detectar duplicados
        person_key = (
            player.first_name.strip(),
            player.last_name.strip(),
            player.birth_date
        )
        
        # Buscar si ya existe esta persona
        if person_key in people_map:
            person = people_map[person_key]
            print(f"✅ Persona duplicada encontrada: {person.first_name} {person.last_name}")
        else:
            # Crear nueva Person
            person = Person.objects.create(
                first_name=player.first_name,
                last_name=player.last_name,
                birth_date=player.birth_date,
                photo=player.photo,
                user=player.user,
                notes=player.notes or "",
                is_active=player.is_active,
                created_at=player.created_at,
            )
            people_map[person_key] = person
            print(f"👤 Creada persona: {person.first_name} {person.last_name}")
        
        # Crear PlayerRole
        player_role = PlayerRole.objects.create(
            person=person,
            team=player.team,
            jersey_number=player.jersey_number,
            position=player.position,
            is_active=player.is_active,
            notes=player.notes or "",
            created_at=player.created_at,
        )
        print(f"🏐 Creado rol de jugador: {player_role}")
    
    # PASO 2: Migrar Staff
    staff_members = Staff.objects.all()
    print(f"📊 Migrando {staff_members.count()} miembros del staff...")
    
    for staff in staff_members:
        # Crear clave única para detectar duplicados
        person_key = (
            staff.first_name.strip(),
            staff.last_name.strip(),
            None  # Staff no tiene birth_date, usar None
        )
        
        # Buscar si ya existe esta persona (por nombre)
        existing_person = None
        for key, person in people_map.items():
            if key[0] == person_key[0] and key[1] == person_key[1]:
                existing_person = person
                break
        
        if existing_person:
            person = existing_person
            # Actualizar contacto si no lo tenía
            if not person.email and staff.email:
                person.email = staff.email
            if not person.phone and staff.phone:
                person.phone = staff.phone
            if not person.photo and staff.photo:
                person.photo = staff.photo
            person.save()
            print(f"✅ Persona existente actualizada: {person.first_name} {person.last_name}")
        else:
            # Crear nueva Person
            person = Person.objects.create(
                first_name=staff.first_name,
                last_name=staff.last_name,
                birth_date=None,
                photo=staff.photo,
                email=staff.email or "",
                phone=staff.phone or "",
                user=staff.user,
                notes=staff.notes or "",
                is_active=staff.is_active,
                created_at=staff.created_at,
            )
            people_map[person_key] = person
            print(f"👤 Creada persona: {person.first_name} {person.last_name}")
        
        # Crear StaffRole
        staff_role = StaffRole.objects.create(
            person=person,
            team=staff.team,
            role=staff.role,
            is_active=staff.is_active,
            notes=staff.notes or "",
            created_at=staff.created_at,
        )
        print(f"💼 Creado rol de staff: {staff_role}")
    
    # ESTADÍSTICAS FINALES
    total_people = Person.objects.count()
    total_player_roles = PlayerRole.objects.count()
    total_staff_roles = StaffRole.objects.count()
    
    print(f"""
🎉 Migración completada exitosamente:
👤 {total_people} personas creadas
🏐 {total_player_roles} roles de jugador creados
💼 {total_staff_roles} roles de staff creados
""")


def reverse_migration(apps, schema_editor):
    """
    Función reversa para deshacer la migración si es necesario.
    ATENCIÓN: Esto eliminará todos los datos de Person, PlayerRole y StaffRole.
    """
    Person = apps.get_model('videos', 'Person')
    PlayerRole = apps.get_model('videos', 'PlayerRole')
    StaffRole = apps.get_model('videos', 'StaffRole')
    
    print("⚠️ ATENCIÓN: Eliminando todos los datos de Person-Role...")
    PlayerRole.objects.all().delete()
    StaffRole.objects.all().delete()
    Person.objects.all().delete()
    print("🗑️ Datos de Person-Role eliminados")


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0020_add_person_role_models'),
    ]

    operations = [
        migrations.RunPython(
            migrate_players_and_staff_to_person_roles,
            reverse_migration,
        ),
    ]
