# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0024_match_acta_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='visibility_type',
            field=models.CharField(
                choices=[
                    ('main', 'Principal (mostrar en app)'),
                    ('reference', 'Referencia (solo admin)'),
                    ('historical', 'Histórica (solo admin)'),
                    ('external', 'Externa (solo admin)')
                ],
                default='main',
                help_text='Controla dónde se muestra la liga: Principal (en la app), Referencia (solo admin), Histórica (datos antiguos), Externa (otras ligas)',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='league',
            name='is_historical',
            field=models.BooleanField(
                default=False,
                help_text='Indica si es una liga de temporadas anteriores'
            ),
        ),
        migrations.AddField(
            model_name='league',
            name='is_our_team_related',
            field=models.BooleanField(
                default=True,
                help_text='Indica si esta liga está relacionada con nuestro equipo'
            ),
        ),
    ]
