# Generated by Django 5.2.7 on 2025-10-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0025_add_league_visibility_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='custom_max_sets',
            field=models.IntegerField(blank=True, help_text='Máximo de sets (solo si formato es personalizado)', null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='custom_sets_to_win',
            field=models.IntegerField(blank=True, help_text='Sets necesarios para ganar (solo si formato es personalizado)', null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='match_format',
            field=models.CharField(choices=[('standard', 'Estándar (5 sets, ganar 3)'), ('alevin_balear', 'Alevín Balear (3 sets, jugar los 3)'), ('tournament_3sets', 'Torneo 3 sets (ganar 2)'), ('custom', 'Personalizado')], default='standard', help_text='Formato de partido para esta liga', max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapingendpoint',
            name='endpoint_type',
            field=models.CharField(choices=[('standings', 'Clasificación'), ('results', 'Resultados'), ('calendar', 'Calendario'), ('json_results', 'Resultados JSON')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapingendpoint',
            name='parser_type',
            field=models.CharField(choices=[('table_standings', 'Tabla de Clasificación'), ('match_results', 'Resultados de Partidos'), ('match_calendar', 'Calendario de Partidos'), ('json_matches', 'Partidos JSON (próximos)'), ('json_results', 'Resultados JSON (finalizados)'), ('json_unified', 'JSON Unificado (configurable)')], max_length=30),
        ),
    ]
