# Generated by Django 5.2.7 on 2025-10-30 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0026_league_custom_max_sets_league_custom_sets_to_win_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='album_group_id',
            field=models.UUIDField(blank=True, help_text='ID de grupo para agrupar imágenes en un álbum sin partido vinculado', null=True),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['album_group_id'], name='videos_imag_album_g_2185c3_idx'),
        ),
    ]
