# Generated by Django 5.2.7 on 2025-10-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0027_image_album_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='album_name',
            field=models.CharField(blank=True, help_text='Nombre del álbum cuando las imágenes están agrupadas sin partido', max_length=200),
        ),
    ]
