# Generated by Django 5.2.7 on 2025-12-30 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0028_image_album_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='display_name_override',
            field=models.CharField(blank=True, help_text='Nombre personalizado para mostrar (opcional)', max_length=200),
        ),
        migrations.AddField(
            model_name='league',
            name='parent_league',
            field=models.ForeignKey(blank=True, help_text='Liga padre si esta es una fase (ej: Liguilla Oro es fase de Liga Regular)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='videos.league'),
        ),
        migrations.AddField(
            model_name='league',
            name='phase_name',
            field=models.CharField(blank=True, help_text='Nombre de la fase (ej: "Liguilla Oro", "Liguilla Plata", "Playoffs")', max_length=100),
        ),
        migrations.AddField(
            model_name='league',
            name='phase_order',
            field=models.IntegerField(default=0, help_text='Orden de la fase (0 = liga principal, 1+ = fases subsecuentes)'),
        ),
        migrations.AddField(
            model_name='team',
            name='is_temporary_variant',
            field=models.BooleanField(default=False, help_text='Marca si es una variante temporal (ej: para un torneo específico)'),
        ),
        migrations.AddField(
            model_name='team',
            name='parent_team',
            field=models.ForeignKey(blank=True, help_text='Equipo principal si este es una variante (ej: Sant Josep A, Sant Josep Groc)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='videos.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='temporary_end_date',
            field=models.DateField(blank=True, help_text='Fecha estimada de finalización si es variante temporal', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='variant_description',
            field=models.TextField(blank=True, help_text='Descripción de la variante'),
        ),
        migrations.AddField(
            model_name='team',
            name='variant_name',
            field=models.CharField(blank=True, help_text='Nombre de la variante (ej: "A", "B", "Groc", "Lila")', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='variant_type',
            field=models.CharField(blank=True, choices=[('split', 'División de Equipo (A/B)'), ('color', 'Variante de Color (Groc/Lila)'), ('temporary', 'Temporal (Torneo)'), ('other', 'Otro')], help_text='Tipo de variante', max_length=20),
        ),
    ]
