# Generated by Django 5.2.7 on 2026-01-02 22:01

from django.db import migrations


def migrate_category_to_categories(apps, schema_editor):
    """
    Migra los datos del campo category (ForeignKey) al nuevo campo categories (ManyToMany)
    """
    League = apps.get_model('videos', 'League')

    # Iterar sobre todas las ligas que tengan una categoría asignada
    for league in League.objects.filter(category__isnull=False):
        # Añadir la categoría al nuevo campo ManyToMany
        league.categories.add(league.category)
        print(f"Migrada categoría para liga: {league.name}")


def reverse_migration(apps, schema_editor):
    """
    Reversión: copiar la primera categoría de categories de vuelta a category
    """
    League = apps.get_model('videos', 'League')

    for league in League.objects.prefetch_related('categories').all():
        if league.categories.exists() and not league.category:
            # Tomar la primera categoría
            first_category = league.categories.first()
            league.category = first_category
            league.save()
            print(f"Revertida categoría para liga: {league.name}")


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0030_add_multi_category_support'),
    ]

    operations = [
        migrations.RunPython(migrate_category_to_categories, reverse_migration),
    ]
