# Generated by Django 6.0.8 on 2026-09-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0035_disable_friendly_scraping_endpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='categories',
            field=models.ManyToManyField(blank=True, db_table='videos_image_categories', help_text='Categorías asociadas a la imagen. Se asigna automáticamente desde el partido o manualmente', related_name='images', to='videos.category'),
        ),
        migrations.AlterField(
            model_name='league',
            name='categories',
            field=models.ManyToManyField(blank=True, db_table='videos_league_categories', help_text='Categorías de la liga (puede ser múltiple para torneos/copas)', related_name='leagues', to='videos.category'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='videos_category',
        ),
        migrations.AlterModelTable(
            name='club',
            table='videos_club',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='videos_comment',
        ),
        migrations.AlterModelTable(
            name='image',
            table='videos_image',
        ),
        migrations.AlterModelTable(
            name='league',
            table='videos_league',
        ),
        migrations.AlterModelTable(
            name='match',
            table='videos_match',
        ),
        migrations.AlterModelTable(
            name='person',
            table='videos_person',
        ),
        migrations.AlterModelTable(
            name='player',
            table='videos_player',
        ),
        migrations.AlterModelTable(
            name='playerrole',
            table='videos_playerrole',
        ),
        migrations.AlterModelTable(
            name='scrapingendpoint',
            table='videos_scrapingendpoint',
        ),
        migrations.AlterModelTable(
            name='staff',
            table='videos_staff',
        ),
        migrations.AlterModelTable(
            name='staffrole',
            table='videos_staffrole',
        ),
        migrations.AlterModelTable(
            name='standing',
            table='videos_standing',
        ),
        migrations.AlterModelTable(
            name='team',
            table='videos_team',
        ),
        migrations.AlterModelTable(
            name='video',
            table='videos_video',
        ),
    ]
