"""
Django settings for videosvoley project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config as env_config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

AUTH_USER_MODEL = 'users.User'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_config('SECRET_KEY', default='django-insecure-x*bcpy_nb811_5s6+7*-0y&mzj36^+v$6rzwglc0v)0j+njp(g')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = env_config('ALLOWED_HOSTS', default='localhost,127.0.0.1,0.0.0.0', cast=lambda v: [s.strip() for s in v.split(',')])
ALLOWED_HOSTS += ['aerologic-nonfluent-jase.ngrok-free.dev']
CSRF_TRUSTED_ORIGINS = env_config('CSRF_TRUSTED_ORIGINS', default='https://aerologic-nonfluent-jase.ngrok-free.dev', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Requerido por allauth

    # Third party
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'django_celery_beat',  # Para gestionar tareas periódicas desde el admin

    # Local apps
    'videosvoley.core.apps.CoreConfig',
    'videosvoley.videos',
    'videosvoley.users',
    'videosvoley.rag',
]

SITE_ID = 1

# Allauth config
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = '/videos/'
LOGOUT_REDIRECT_URL = '/'

# Allauth settings (nueva sintaxis)
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']

# Suprimir mensajes automáticos de allauth
ACCOUNT_SESSION_REMEMBER = None
SOCIALACCOUNT_AUTO_SIGNUP = True
ACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'

# Configurar qué mensajes de allauth mostrar
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True

# Configuración para login con Google
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_STORE_TOKENS = True
SOCIALACCOUNT_AUTO_SIGNUP = True  # Auto-crear cuenta si no existe
ACCOUNT_EMAIL_VERIFICATION = 'none'  # No requerir verificación de email
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True  # Permitir login automático si el email coincide
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True  # Conectar automáticamente si el email existe

# Configuración de Google Calendar API
# Scopes básicos para todos los usuarios
GOOGLE_BASIC_SCOPES = [
    'profile',
    'email',
]



SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': GOOGLE_BASIC_SCOPES,  # Solo scopes básicos por defecto
        'AUTH_PARAMS': {
            'access_type': 'offline',
            'prompt': 'consent'
        }
    }
}

# Forzar HTTPS solo en producción
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'http' if DEBUG else 'https'

# Header de proxy SSL (necesario para que Django detecte HTTPS detrás de nginx)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')



# Adapters personalizados para suprimir mensajes
ACCOUNT_ADAPTER = 'videosvoley.users.adapters.CustomAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'videosvoley.users.adapters.CustomSocialAccountAdapter'

# Formulario personalizado de registro
ACCOUNT_SIGNUP_FORM_CLASS = 'videosvoley.users.forms.CustomSignupForm'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'videosvoley.core.middleware.Error404TrackingMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'videosvoley/templates')],  # <-- Añadir esta línea
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env_config('DB_NAME', default='volleyvideos'),
        'USER': env_config('DB_USER', default='volleyuser'),
        'PASSWORD': env_config('DB_PASSWORD', default='volleypass'),
        'HOST': env_config('DB_HOST', default='db'),
        'PORT': env_config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ES'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'videosvoley/static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuración de subida de archivos
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10MB

# Configuración para Google Vision API (opcional)
GOOGLE_VISION_ENABLED = env_config('GOOGLE_VISION_ENABLED', default=False, cast=bool)
GOOGLE_APPLICATION_CREDENTIALS = env_config('GOOGLE_APPLICATION_CREDENTIALS', default='')

# Configuración de moderación automática
AUTO_MODERATION_ENABLED = env_config('AUTO_MODERATION_ENABLED', default=DEBUG, cast=bool)

# Configuración específica del club
CLUB_TEAM_NAME = 'SANT JOSEP'  # Nombre del equipo principal para filtrar videos y equipos del club

# Email configuration
EMAIL_BACKEND = env_config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = env_config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env_config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = env_config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = env_config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env_config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env_config('DEFAULT_FROM_EMAIL', default='Admin I Love Voley <josealbertomartin@gmail.com>')
SERVER_EMAIL = env_config('SERVER_EMAIL', default='Admin I Love Voley <josealbertomartin@gmail.com>')

# Notificaciones
NOTIFICATION_EMAIL_ENABLED = env_config('NOTIFICATION_EMAIL_ENABLED', default=False, cast=bool)
ADMIN_EMAIL_LIST = env_config('ADMIN_EMAIL_LIST', default='', cast=lambda v: [s.strip() for s in v.split(',') if s.strip()])

# Configuración específica de notificaciones
EMAIL_NOTIFICATIONS = {
    'new_user_pending': env_config('EMAIL_NOTIFY_NEW_USER', default=True, cast=bool),
    'user_approved': env_config('EMAIL_NOTIFY_USER_APPROVED', default=True, cast=bool),
    'image_pending': env_config('EMAIL_NOTIFY_IMAGE_PENDING', default=True, cast=bool),
    'image_moderated': env_config('EMAIL_NOTIFY_IMAGE_MODERATED', default=True, cast=bool),
    'error_404_daily': env_config('EMAIL_NOTIFY_404_DAILY', default=False, cast=bool),
}

# Celery Configuration
CELERY_BROKER_URL = env_config('REDIS_URL', default='redis://redis:6379/0')
CELERY_RESULT_BACKEND = env_config('REDIS_URL', default='redis://redis:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Celery Beat Configuration (Periodic Tasks)
CELERY_BEAT_SCHEDULE = {
    'rag-incremental-reindex': {
        'task': 'videosvoley.rag.tasks.incremental_reindex_task',
        'schedule': 3600.0 * 6,  # Run every 6 hours
        'options': {'expire_seconds': 3600}  # Expire after 1 hour if not executed
    },
}

# Admin URL Configuration
# En producción (DEBUG=False) usa la URL cifrada del .env
# En desarrollo (DEBUG=True) siempre usa 'admin/' para facilitar el desarrollo
if DEBUG:
    ADMIN_URL = 'admin/'
else:
    ADMIN_URL = env_config('DJANGO_ADMIN_URL', default='admin/')

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'videosvoley': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'rag': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Configuración del sistema RAG
OLLAMA_HOST = env_config('OLLAMA_HOST', default='http://192.168.0.16:11434')  # Cambia por tu IP del servidor
CHROMA_COLLECTION_NAME = env_config('CHROMA_COLLECTION_NAME', default='videosvoley_docs')
CHROMA_PERSIST_DIR = env_config('CHROMA_PERSIST_DIR', default=os.path.join(BASE_DIR, 'chroma_db'))
EMBEDDING_MODEL = env_config('EMBEDDING_MODEL', default='sentence-transformers/all-MiniLM-L6-v2')
DEFAULT_OLLAMA_MODEL = env_config('DEFAULT_OLLAMA_MODEL', default='phi3:mini')
