"""
Django settings for ilovevoley project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config as env_config
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.csp import CSP
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

AUTH_USER_MODEL = 'users.User'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = env_config('ALLOWED_HOSTS', default='localhost,127.0.0.1,0.0.0.0', cast=lambda v: [s.strip() for s in v.split(',')])
CSRF_TRUSTED_ORIGINS = env_config(
    'CSRF_TRUSTED_ORIGINS',
    default='',
    cast=lambda v: [s.strip() for s in v.split(',') if s.strip()],
)

# Dominios oficiales de federación permitidos al descargar actas (mitigación SSRF).
ACTA_ALLOWED_HOSTS = env_config(
    'ACTA_ALLOWED_HOSTS',
    default='federatio.com,voleibolib.net,voleibolib.es,rfevb.com',
    cast=lambda v: [s.strip() for s in v.split(',') if s.strip()],
)


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.inlines',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Requerido por allauth

    # Third party
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'django_celery_beat',  # Para gestionar tareas periódicas desde el admin

    # Local apps
    'ilovevoley.core.apps.CoreConfig',
    'ilovevoley.rosters',
    'ilovevoley.content',
    'ilovevoley.teams',
    'ilovevoley.competitions',
    'ilovevoley.videos',
    'ilovevoley.users',
]

SITE_ID = 1

# Allauth config
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = '/videos/'
LOGOUT_REDIRECT_URL = '/'

# Allauth settings (nueva sintaxis)
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']

# Suprimir mensajes automáticos de allauth
ACCOUNT_SESSION_REMEMBER = None

# Verificación de email opcional: los registros locales reciben el correo de
# verificación, pero pueden entrar sin confirmarlo. La autenticación por email
# de un login social solo se permite si la cuenta local verificó su email
# (ver CustomSocialAccountAdapter.authenticate_by_email), de modo que una
# cuenta local no verificada no puede absorber el login social de la víctima.
ACCOUNT_EMAIL_VERIFICATION = 'optional'
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'

# Configurar qué mensajes de allauth mostrar
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True

# Configuración para login con Google
SOCIALACCOUNT_AUTO_SIGNUP = True  # Auto-crear cuenta si no existe
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_STORE_TOKENS = False  # No almacenar access/refresh tokens de Google
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True  # Permitir login si el email coincide con una cuenta local verificada
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True  # Vincular la cuenta social a la local verificada

# Configuración de Google Calendar API
# Scopes básicos para todos los usuarios
GOOGLE_BASIC_SCOPES = [
    'profile',
    'email',
]



SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': GOOGLE_BASIC_SCOPES,  # Solo scopes básicos por defecto
        'AUTH_PARAMS': {
            'prompt': 'consent'
        }
    }
}

# Forzar HTTPS solo en producción
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'http' if DEBUG else 'https'

# Header de proxy SSL (necesario para que Django detecte HTTPS detrás de nginx)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cabeceras de transporte seguro y cookies (activas por defecto en producción)
SESSION_COOKIE_SECURE = env_config('SESSION_COOKIE_SECURE', default=not DEBUG, cast=bool)
CSRF_COOKIE_SECURE = env_config('CSRF_COOKIE_SECURE', default=not DEBUG, cast=bool)
SESSION_COOKIE_HTTPONLY = True

SECURE_SSL_REDIRECT = env_config('SECURE_SSL_REDIRECT', default=not DEBUG, cast=bool)
SECURE_HSTS_SECONDS = env_config('SECURE_HSTS_SECONDS', default=31536000 if not DEBUG else 0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=not DEBUG, cast=bool)
SECURE_HSTS_PRELOAD = env_config('SECURE_HSTS_PRELOAD', default=False, cast=bool)

# Content Security Policy (CSP Report-Only nativo Django 6.0)
SECURE_CSP = None
SECURE_CSP_REPORT_ONLY = {
    'default-src': [CSP.SELF],
    'script-src': [
        CSP.SELF,
        CSP.UNSAFE_INLINE,
        CSP.UNSAFE_EVAL,
        'https://cdn.tailwindcss.com',
        'https://cdn.jsdelivr.net',
        'https://cdnjs.cloudflare.com',
        'https://www.instagram.com',
    ],
    'style-src': [
        CSP.SELF,
        CSP.UNSAFE_INLINE,
        'https://cdn.jsdelivr.net',
        'https://cdnjs.cloudflare.com',
    ],
    'img-src': [
        CSP.SELF,
        'data:',
        'blob:',
        'https://*.googleusercontent.com',
        'https://img.youtube.com',
        'https://i.ytimg.com',
    ],
    'font-src': [CSP.SELF, 'data:'],
    'frame-src': [
        CSP.SELF,
        'https://www.youtube.com',
        'https://www.youtube-nocookie.com',
        'https://www.instagram.com',
    ],
    'connect-src': [CSP.SELF],
    'object-src': [CSP.NONE],
    'base-uri': [CSP.SELF],
    'form-action': [CSP.SELF],
}

# Adapters personalizados para suprimir mensajes
ACCOUNT_ADAPTER = 'ilovevoley.users.adapters.CustomAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'ilovevoley.users.adapters.CustomSocialAccountAdapter'

# Formulario personalizado de registro
ACCOUNT_SIGNUP_FORM_CLASS = 'ilovevoley.users.forms.CustomSignupForm'

MIDDLEWARE = [
    'ilovevoley.core.middleware.TenantMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.csp.ContentSecurityPolicyMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'ilovevoley.core.middleware.Error404TrackingMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'ilovevoley/templates')],  # <-- Añadir esta línea
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ilovevoley.core.context_processors.tenant_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env_config('DB_NAME', default='volleyvideos'),
        'USER': env_config('DB_USER', default='volleyuser'),
        # Required when DEBUG=False; local default only for docker-compose.dev.
        'PASSWORD': (
            env_config('DB_PASSWORD', default='volleypass')
            if DEBUG
            else env_config('DB_PASSWORD')
        ),
        'HOST': env_config('DB_HOST', default='db'),
        'PORT': env_config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ES'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'ilovevoley/static'),
]

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'ilovevoley.core.storage.ForgivingManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Medios privados: nginx reenvía /media/ a Django y este autoriza y delega la
# entrega del archivo vía X-Accel-Redirect a la zona interna /protected-media/.
# En desarrollo (DEBUG) se sirve directamente con FileResponse.
PROTECTED_MEDIA_USE_X_ACCEL = env_config('PROTECTED_MEDIA_USE_X_ACCEL', default=not DEBUG, cast=bool)
PROTECTED_MEDIA_INTERNAL_URL = '/protected-media/'

# Configuración de subida de archivos
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10MB

# Configuración para Google Vision API (opcional)
GOOGLE_VISION_ENABLED = env_config('GOOGLE_VISION_ENABLED', default=False, cast=bool)
GOOGLE_APPLICATION_CREDENTIALS = env_config('GOOGLE_APPLICATION_CREDENTIALS', default='')

# Configuración de moderación automática
AUTO_MODERATION_ENABLED = env_config('AUTO_MODERATION_ENABLED', default=DEBUG, cast=bool)

# Configuración específica del club
CLUB_TEAM_NAME = 'SANT JOSEP'  # Nombre del equipo principal para filtrar videos y equipos del club

# Email configuration
EMAIL_BACKEND = env_config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = env_config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env_config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = env_config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = env_config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env_config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env_config('DEFAULT_FROM_EMAIL', default='Admin I Love Voley <josealbertomartin@gmail.com>')
SERVER_EMAIL = env_config('SERVER_EMAIL', default='Admin I Love Voley <josealbertomartin@gmail.com>')

# Notificaciones
NOTIFICATION_EMAIL_ENABLED = env_config('NOTIFICATION_EMAIL_ENABLED', default=False, cast=bool)
ADMIN_EMAIL_LIST = env_config('ADMIN_EMAIL_LIST', default='', cast=lambda v: [s.strip() for s in v.split(',') if s.strip()])

# Configuración específica de notificaciones
EMAIL_NOTIFICATIONS = {
    'new_user_pending': env_config('EMAIL_NOTIFY_NEW_USER', default=True, cast=bool),
    'user_approved': env_config('EMAIL_NOTIFY_USER_APPROVED', default=True, cast=bool),
    'image_pending': env_config('EMAIL_NOTIFY_IMAGE_PENDING', default=True, cast=bool),
    'image_moderated': env_config('EMAIL_NOTIFY_IMAGE_MODERATED', default=True, cast=bool),
    'error_404_daily': env_config('EMAIL_NOTIFY_404_DAILY', default=False, cast=bool),
}

# Celery Configuration
CELERY_BROKER_URL = env_config('REDIS_URL', default='redis://redis:6379/0')
CELERY_RESULT_BACKEND = env_config('REDIS_URL', default='redis://redis:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Celery Beat Configuration (Periodic Tasks)
CELERY_BEAT_SCHEDULE = {}

# Cache Configuration
# Redis backend centralizado (DB 1 reservada para caché, DB 0 para Celery)
REDIS_CACHE_URL = env_config('REDIS_CACHE_URL', default='redis://redis:6379/1')

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': REDIS_CACHE_URL,
    }
}

# Admin URL Configuration
# En producción (DEBUG=False) usa la URL cifrada del .env
# En desarrollo (DEBUG=True) siempre usa 'admin/' para facilitar el desarrollo
if DEBUG:
    ADMIN_URL = 'admin/'
else:
    ADMIN_URL = env_config('DJANGO_ADMIN_URL', default='admin/')

UNFOLD = {
    'SITE_TITLE': 'ilovevoley',
    'SITE_HEADER': 'ilovevoley',
    'SITE_SUBHEADER': _('Panel de administración'),
    'SITE_URL': '/',
    'SITE_SYMBOL': 'sports_volleyball',
    'SITE_ICON': lambda request: static('images/favicon.svg'),
    'SITE_LOGO': lambda request: static('images/logo.svg'),
    'SITE_DROPDOWN': [
        {
            'icon': 'home',
            'title': _('Ir al sitio web'),
            'link': '/',
        },
        {
            'icon': 'photo_library',
            'title': _('Galería de fotos'),
            'link': '/videos/imagenes/',
        },
        {
            'icon': 'calendar_month',
            'title': _('Calendario de partidos'),
            'link': '/videos/calendario/',
        },
    ],
    'ENVIRONMENT': 'ilovevoley.core.unfold_callbacks.environment_callback',
    'BORDER_RADIUS': '10px',
    'SHOW_HISTORY': True,
    'SHOW_VIEW_ON_SITE': True,
    'SHOW_BACK_BUTTON': True,
    'COLORS': {
        'base': {
            '50': 'oklch(98.5% 0.004 220)',
            '100': 'oklch(96% 0.008 220)',
            '200': 'oklch(91% 0.012 220)',
            '300': 'oklch(84% 0.016 220)',
            '400': 'oklch(68% 0.022 220)',
            '500': 'oklch(52% 0.026 220)',
            '600': 'oklch(44% 0.028 220)',
            '700': 'oklch(37% 0.028 220)',
            '800': 'oklch(28% 0.024 220)',
            '900': 'oklch(21% 0.02 220)',
            '950': 'oklch(14% 0.016 220)',
        },
        'primary': {
            '50': 'oklch(97% 0.02 195)',
            '100': 'oklch(93% 0.04 195)',
            '200': 'oklch(86% 0.06 195)',
            '300': 'oklch(76% 0.08 195)',
            '400': 'oklch(62% 0.09 195)',
            '500': 'oklch(50% 0.09 195)',
            '600': 'oklch(44% 0.08 195)',
            '700': 'oklch(38% 0.07 195)',
            '800': 'oklch(32% 0.06 195)',
            '900': 'oklch(26% 0.05 195)',
            '950': 'oklch(20% 0.04 195)',
        },
        'font': {
            'subtle-light': 'var(--color-base-500)',
            'subtle-dark': 'var(--color-base-400)',
            'default-light': 'var(--color-base-600)',
            'default-dark': 'var(--color-base-300)',
            'important-light': 'var(--color-base-900)',
            'important-dark': 'var(--color-base-100)',
        },
    },
    'STYLES': [
        lambda request: static('admin/css/unfold_custom.css'),
    ],
    'SIDEBAR': {
        'show_search': True,
        'show_all_applications': True,
        'navigation': [
            {
                'title': _('Inicio'),
                'separator': True,
                'items': [
                    {
                        'title': _('Panel principal'),
                        'icon': 'dashboard',
                        'link': reverse_lazy('admin:index'),
                    },
                ],
            },
            {
                'title': _('Moderación'),
                'separator': True,
                'collapsible': False,
                'items': [
                    {
                        'title': _('Fotos pendientes'),
                        'icon': 'photo_camera',
                        'link': f"/{ADMIN_URL}content/image/?status__exact=pending",
                        'badge': 'ilovevoley.core.unfold_callbacks.pending_images_badge',
                        'badge_variant': 'warning',
                    },
                    {
                        'title': _('Usuarios pendientes'),
                        'icon': 'person_add',
                        'link': f"/{ADMIN_URL}users/user/?is_approved__exact=0",
                        'badge': 'ilovevoley.core.unfold_callbacks.pending_users_badge',
                        'badge_variant': 'warning',
                    },
                    {
                        'title': _('Membresías pendientes'),
                        'icon': 'group_add',
                        'link': f"/{ADMIN_URL}users/membership/?is_approved__exact=0",
                        'badge': 'ilovevoley.core.unfold_callbacks.pending_memberships_badge',
                        'badge_variant': 'info',
                    },
                ],
            },
            {
                'title': _('Contenido'),
                'collapsible': True,
                'items': [
                    {
                        'title': _('Todas las fotos'),
                        'icon': 'image',
                        'link': reverse_lazy('admin:content_image_changelist'),
                    },
                    {
                        'title': _('Videos'),
                        'icon': 'videocam',
                        'link': reverse_lazy('admin:content_video_changelist'),
                    },
                    {
                        'title': _('Partidos'),
                        'icon': 'sports_volleyball',
                        'link': reverse_lazy('admin:competitions_match_changelist'),
                    },
                ],
            },
            {
                'title': _('Club y plantilla'),
                'collapsible': True,
                'items': [
                    {
                        'title': _('Personas'),
                        'icon': 'badge',
                        'link': reverse_lazy('admin:rosters_person_changelist'),
                    },
                    {
                        'title': _('Equipos'),
                        'icon': 'groups',
                        'link': reverse_lazy('admin:teams_team_changelist'),
                    },
                    {
                        'title': _('Clasificaciones'),
                        'icon': 'leaderboard',
                        'link': reverse_lazy('admin:competitions_standing_changelist'),
                    },
                    {
                        'title': _('Categorías'),
                        'icon': 'category',
                        'link': reverse_lazy('admin:core_category_changelist'),
                    },
                ],
            },
            {
                'title': _('Competiciones'),
                'collapsible': True,
                'items': [
                    {
                        'title': _('Ligas'),
                        'icon': 'emoji_events',
                        'link': reverse_lazy('admin:competitions_league_changelist'),
                    },
                    {
                        'title': _('Temporadas'),
                        'icon': 'calendar_month',
                        'link': reverse_lazy('admin:core_season_changelist'),
                    },
                    {
                        'title': _('Clubes'),
                        'icon': 'stadium',
                        'link': reverse_lazy('admin:teams_club_changelist'),
                    },
                ],
            },
            {
                'title': _('Usuarios'),
                'collapsible': True,
                'items': [
                    {
                        'title': _('Todos los usuarios'),
                        'icon': 'people',
                        'link': reverse_lazy('admin:users_user_changelist'),
                    },
                    {
                        'title': _('Membresías'),
                        'icon': 'card_membership',
                        'link': reverse_lazy('admin:users_membership_changelist'),
                    },
                ],
            },
            {
                'title': _('Sistema'),
                'collapsible': True,
                'items': [
                    {
                        'title': _('Organizaciones'),
                        'icon': 'domain',
                        'link': reverse_lazy('admin:core_organization_changelist'),
                        'permission': 'ilovevoley.core.unfold_callbacks.is_superuser',
                    },
                    {
                        'title': _('Tareas programadas'),
                        'icon': 'schedule',
                        'link': reverse_lazy('admin:django_celery_beat_periodictask_changelist'),
                        'permission': 'ilovevoley.core.unfold_callbacks.is_superuser',
                    },
                    {
                        'title': _('Endpoints de scraping'),
                        'icon': 'cloud_download',
                        'link': reverse_lazy('admin:competitions_scrapingendpoint_changelist'),
                        'permission': 'ilovevoley.core.unfold_callbacks.is_superuser',
                    },
                ],
            },
        ],
    },
}

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'ilovevoley': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Multi-tenant: cookie compartida entre subdominios en producción
SESSION_COOKIE_DOMAIN = env_config('SESSION_COOKIE_DOMAIN', default=None if DEBUG else '.ilovevoley.es')
CSRF_COOKIE_DOMAIN = env_config('SESSION_COOKIE_DOMAIN', default=None if DEBUG else '.ilovevoley.es')
TENANT_BASE_DOMAIN = env_config('TENANT_BASE_DOMAIN', default='localhost:8000')

# Sentry error tracking and performance monitoring
from config.sentry import configure as _configure_sentry
_configure_sentry(
    dsn=env_config('SENTRY_DSN', default=''),
    debug=DEBUG,
    traces_sample_rate=env_config('SENTRY_TRACES_SAMPLE_RATE', default=0.1, cast=float),
    release=env_config('SENTRY_RELEASE', default=None),
    environment=env_config('SENTRY_ENVIRONMENT', default='production'),
)
