# Generated by Django 5.2.7 on 2025-10-26 19:26

import django.core.validators
import django.db.models.deletion
import videosvoley.content.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0026_league_custom_max_sets_league_custom_sets_to_win_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_videos', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_videos', to='videos.match')),
            ],
            options={
                'verbose_name': 'Vídeo',
                'verbose_name_plural': 'Vídeos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_comments', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.video')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Formatos permitidos: JPG, PNG, WebP, HEIC. Tamaño máximo: 10MB', upload_to=videosvoley.content.models.image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'heic', 'heif'])])),
                ('title', models.CharField(help_text='Título descriptivo de la imagen', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción opcional')),
                ('original_format', models.CharField(blank=True, help_text='Formato original del archivo (ej: heic, jpg)', max_length=10)),
                ('was_converted', models.BooleanField(default=False, help_text='Indica si la imagen fue convertida desde otro formato')),
                ('image_type', models.CharField(choices=[('match', 'Partido'), ('celebration', 'Celebración'), ('training', 'Entrenamiento'), ('team_photo', 'Foto de Equipo'), ('facilities', 'Instalaciones'), ('other', 'Otro')], default='other', help_text='Tipo de imagen', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Etiquetas separadas por comas (ej: gol, victoria, senior)', max_length=500)),
                ('auto_tags', models.JSONField(blank=True, default=list, help_text='Etiquetas detectadas automáticamente por Vision API')),
                ('year', models.IntegerField(help_text='Año de la temporada')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de Moderación'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', help_text='Estado de moderación', max_length=20)),
                ('moderation_date', models.DateTimeField(blank=True, null=True)),
                ('moderation_notes', models.TextField(blank=True, help_text='Notas internas de moderación')),
                ('vision_api_checked', models.BooleanField(default=False)),
                ('vision_api_safe', models.BooleanField(default=True)),
                ('vision_api_details', models.JSONField(blank=True, default=dict)),
                ('categories', models.ManyToManyField(blank=True, help_text='Categorías asociadas a la imagen. Se asigna automáticamente desde el partido o manualmente', related_name='images', to='content.category')),
                ('match', models.ForeignKey(blank=True, help_text='Partido al que pertenece la imagen (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_images', to='videos.match')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_moderated_images', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['status'], name='content_ima_status_f1efcf_idx'), models.Index(fields=['match'], name='content_ima_match_i_837b01_idx'), models.Index(fields=['year'], name='content_ima_year_922109_idx'), models.Index(fields=['upload_date'], name='content_ima_upload__62a00f_idx'), models.Index(fields=['image_type'], name='content_ima_image_t_b24b97_idx')],
            },
        ),
    ]
