# Generated by Django 5.2.7 on 2025-01-27 12:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_image_match_alter_video_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='album_group_id',
            field=models.UUIDField(blank=True, help_text='ID de grupo para agrupar imágenes en un álbum sin partido vinculado', null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='album_name',
            field=models.CharField(blank=True, help_text='Nombre del álbum cuando las imágenes están agrupadas sin partido', max_length=200),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['album_group_id'], name='content_imag_album_g_idx'),
        ),
    ]
