# Generated by Django 6.0.8 on 2026-09-20 14:31
# Ajustada a mano: sustituye Image.year por una FK a core.Season y añade
# Video.season, rellenando ambas con la temporada del partido o, si no hay
# partido, con la inferida de la fecha de subida (corte 1 de septiembre).

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone

from videosvoley.core.models import normalize_season_name, season_start_year_for_date


def _resolve(Season, cache, name):
    name = normalize_season_name(name)
    if not name:
        return None
    if name in cache:
        return cache[name]
    start_year = int(name.split('-')[0])
    season, _ = Season.objects.get_or_create(
        name=name,
        defaults={'start_year': start_year, 'end_year': start_year + 1},
    )
    cache[name] = season
    return season


def _for_date(Season, cache, value):
    start_year = season_start_year_for_date(value)
    return _resolve(Season, cache, f'{start_year}-{start_year + 1}')


def backfill_image_season(apps, schema_editor):
    Image = apps.get_model('content', 'Image')
    Season = apps.get_model('core', 'Season')
    cache = {}
    for image in Image.objects.select_related('match__league__season'):
        season = None
        if image.match_id:
            match = image.match
            if match.league_id and match.league.season_id:
                season = _resolve(Season, cache, match.league.season.name)
            elif match.match_date:
                season = _for_date(Season, cache, match.match_date)
        if season is None:
            season = _for_date(Season, cache, image.upload_date or timezone.now())
        if season is not None:
            image.season_id = season.pk
            image.save(update_fields=['season'])


def backfill_video_season(apps, schema_editor):
    Video = apps.get_model('content', 'Video')
    Season = apps.get_model('core', 'Season')
    cache = {}
    for video in Video.objects.select_related('match__league__season'):
        season = None
        if video.match_id:
            match = video.match
            if match.league_id and match.league.season_id:
                season = _resolve(Season, cache, match.league.season.name)
            elif match.match_date:
                season = _for_date(Season, cache, match.match_date)
        if season is None:
            season = _for_date(Season, cache, video.created_at or timezone.now())
        if season is not None:
            video.season_id = season.pk
            video.save(update_fields=['season'])


def reverse_backfill(apps, schema_editor):
    # Al revertir, las columnas de temporada se eliminan igualmente; no hay
    # nada que restaurar desde la FK al antiguo entero/char.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_image_categories_alter_video_category'),
        ('core', '0007_season'),
        ('competitions', '0005_alter_league_unique_together_alter_league_season'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='image',
            name='videos_imag_year_e48770_idx',
        ),
        migrations.AddField(
            model_name='image',
            name='season',
            field=models.ForeignKey(blank=True, help_text='Temporada a la que pertenece la imagen', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='core.season', verbose_name='Temporada'),
        ),
        migrations.RunPython(backfill_image_season, reverse_backfill),
        migrations.AddField(
            model_name='video',
            name='season',
            field=models.ForeignKey(blank=True, help_text='Temporada a la que pertenece el vídeo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='core.season', verbose_name='Temporada'),
        ),
        migrations.RunPython(backfill_video_season, reverse_backfill),
        migrations.RemoveField(
            model_name='image',
            name='year',
        ),
    ]
