# Generated by Django 5.2.7 on 2025-11-06 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        ('content', '0003_image_album_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='image',
            new_name='content_ima_album_g_d38c8b_idx',
            old_name='content_imag_album_g_idx',
        ),
        migrations.AlterField(
            model_name='image',
            name='match',
            field=models.ForeignKey(blank=True, help_text='Partido al que pertenece la imagen (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_images', to='competitions.match'),
        ),
        migrations.AlterField(
            model_name='video',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_videos', to='competitions.match'),
        ),
    ]
