# Generated by Django 6.0.8 on 2026-09-19 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0038_move_content_to_app'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Club',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('federation_id', models.CharField(max_length=200, unique=True)),
                        ('official_name', models.CharField(max_length=200)),
                        ('president', models.CharField(blank=True, max_length=200)),
                        ('address', models.TextField(blank=True)),
                        ('phone', models.CharField(blank=True, max_length=50)),
                        ('email', models.EmailField(blank=True, max_length=254)),
                        ('venue_name', models.CharField(blank=True, max_length=200)),
                        ('venue_address', models.CharField(blank=True, max_length=200)),
                        ('province', models.CharField(blank=True, max_length=100)),
                        ('instagram', models.URLField(blank=True)),
                        ('facebook', models.URLField(blank=True)),
                        ('twitter', models.URLField(blank=True)),
                        ('website', models.URLField(blank=True)),
                        ('logo_url', models.URLField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'verbose_name': 'Club',
                        'verbose_name_plural': 'Clubes',
                        'db_table': 'videos_club',
                        'ordering': ['official_name'],
                    },
                ),
                migrations.CreateModel(
                    name='Team',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=200)),
                        ('federation_id', models.CharField(max_length=200, unique=True)),
                        ('sponsor_name', models.CharField(blank=True, help_text='Nombre con patrocinador si aplica', max_length=200)),
                        ('logo_url', models.URLField(blank=True, null=True)),
                        ('is_active', models.BooleanField(default=True, help_text='Indica si el equipo sigue activo en las competiciones')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('variant_type', models.CharField(blank=True, choices=[('split', 'División de Equipo (A/B)'), ('color', 'Variante de Color (Groc/Lila)'), ('temporary', 'Temporal (Torneo)'), ('other', 'Otro')], help_text='Tipo de variante', max_length=20)),
                        ('variant_name', models.CharField(blank=True, help_text='Nombre de la variante (ej: "A", "B", "Groc", "Lila")', max_length=50)),
                        ('variant_description', models.TextField(blank=True, help_text='Descripción de la variante')),
                        ('is_temporary_variant', models.BooleanField(default=False, help_text='Marca si es una variante temporal (ej: para un torneo específico)')),
                        ('temporary_end_date', models.DateField(blank=True, help_text='Fecha estimada de finalización si es variante temporal', null=True)),
                        ('category', models.ForeignKey(blank=True, help_text='Categoría asignada automáticamente durante el scraping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='videos.category')),
                        ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='teams.club')),
                        ('parent_team', models.ForeignKey(blank=True, help_text='Equipo principal si este es una variante (ej: Sant Josep A, Sant Josep Groc)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='teams.team')),
                    ],
                    options={
                        'verbose_name': 'Equipo',
                        'verbose_name_plural': 'Equipos',
                        'db_table': 'videos_team',
                        'ordering': ['name'],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
