# Generated by Django 6.0.8 on 2026-09-19 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_move_category_to_core'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Categoría asignada automáticamente durante el scraping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='core.category'),
        ),
    ]
