# Generated by Django 6.0.8 on 2026-09-30 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_venue_match_venue_ref'),
        ('teams', '0003_backfill_team_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='default_venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='competitions.venue', verbose_name='Pabellón habitual'),
        ),
    ]
