# Generated by Django 6.0.8 on 2026-10-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_club_default_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Sin especificar'), ('male', 'Masculino'), ('female', 'Femenino'), ('mixed', 'Mixto')], default='', help_text='Vacío = hereda el género de la categoría.', max_length=10, verbose_name='Género / Rama'),
        ),
    ]
