# Generated by Django 6.0.8 on 2026-10-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='municipality',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
