# Generated by Django 6.0.8 on 2026-10-05 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_club_municipality'),
        ('teams', '0006_fix_team_club_from_matches'),
    ]

    operations = [
    ]
