# Generated by Django 6.0.8 on 2026-10-07 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_backfill_santjosep_gradient_color'),
        ('teams', '0007_merge_20261006_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('', 'Sin especificar'), ('male', 'Masculino'), ('female', 'Femenino'), ('mixed', 'Mixto')], default='', max_length=10)),
                ('core_name', models.CharField(max_length=200)),
                ('core_name_normalized', models.CharField(db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_identities', to='core.category')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_identities', to='teams.club')),
            ],
            options={
                'verbose_name': 'Identidad de equipo',
                'verbose_name_plural': 'Identidades de equipo',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='identity',
            field=models.ForeignKey(blank=True, help_text='Identidad estable entre temporadas (no confundir con federation_id ni con variantes)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='teams.teamidentity'),
        ),
        migrations.CreateModel(
            name='TeamIdentityCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_candidates', to='teams.team')),
                ('suggested_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.teamidentity')),
                ('suggested_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team')),
            ],
            options={
                'verbose_name': 'Candidata de identidad de equipo',
                'verbose_name_plural': 'Candidatas de identidad de equipo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='teamidentity',
            constraint=models.UniqueConstraint(condition=models.Q(('club__isnull', False)), fields=('club', 'category', 'gender', 'core_name_normalized'), name='unique_team_identity_per_club_category_gender_name'),
        ),
    ]
