# Generated by Django 6.0.8 on 2026-10-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_merge_20261006_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, upload_to='clubs/logos/', verbose_name='Escudo (copia local)'),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, upload_to='teams/logos/', verbose_name='Escudo (copia local)'),
        ),
    ]
