# Generated by Django 5.2.7 on 2026-06-02 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Organización', 'verbose_name_plural': 'Organizaciones'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='primary_color',
            field=models.CharField(default='#9B7FBF', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Introduce un color hexadecimal válido (ej: #9B7FBF)')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='secondary_color',
            field=models.CharField(blank=True, default='#7B5FA0', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Introduce un color hexadecimal válido (ej: #9B7FBF)')]),
        ),
    ]
