# Generated by Django 6.0.8 on 2026-09-19 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organization_club'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='club',
            field=models.ForeignKey(blank=True, help_text='Club federativo vinculado (opcional; null p.ej. para selecciones)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='teams.club'),
        ),
    ]
