# Generated by Django 5.2.7 on 2025-10-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_calendar_token'),
        ('videos', '0022_alter_person_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='children',
            field=models.ManyToManyField(blank=True, help_text='Fichas de los hijos que puedes editar', related_name='parents', to='videos.person', verbose_name='Hijos'),
        ),
    ]
