# Generated by Django 6.0.8 on 2026-09-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_move_category_to_core'),
        ('users', '0009_alter_user_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_categories',
            field=models.ManyToManyField(blank=True, help_text='Categorías de contenido que deseas ver', related_name='subscribed_users', to='core.category', verbose_name='Categorías de Interés'),
        ),
    ]
