# Generated by Django 6.0.8 on 2026-09-25 17:58

from django.db import migrations


def migrate_videomanagers_to_membership(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Membership = apps.get_model('users', 'Membership')
    Video = apps.get_model('content', 'Video')
    Image = apps.get_model('content', 'Image')

    try:
        group = Group.objects.get(name='VideoManagers')
    except Group.DoesNotExist:
        return

    users = list(group.user_set.all())
    for user in users:
        org_ids = set(
            Video.objects.filter(created_by=user, organization__isnull=False)
            .values_list('organization_id', flat=True)
        )
        org_ids.update(
            Image.objects.filter(uploaded_by=user, organization__isnull=False)
            .values_list('organization_id', flat=True)
        )

        if org_ids:
            # Solo elevar en organizaciones donde el usuario creó contenido.
            Membership.objects.filter(
                user=user,
                role='member',
                organization_id__in=org_ids,
            ).update(role='manager', is_approved=True)

            for org_id in org_ids:
                Membership.objects.get_or_create(
                    user=user,
                    organization_id=org_id,
                    defaults={'role': 'manager', 'is_approved': True},
                )

        group.user_set.remove(user)


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_organization_default_home'),
        ('content', '0004_remove_image_videos_imag_year_e48770_idx_and_more'),
        ('users', '0010_alter_user_preferred_categories'),
    ]

    operations = [
        migrations.RunPython(
            migrate_videomanagers_to_membership,
            reverse_code=reverse_migration,
        ),
    ]
