# Generated by Django 6.0.8 on 2026-09-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_migrate_videomanagers_to_membership'),
        ('users', '0011_purge_socialaccount_tokens'),
    ]

    operations = [
    ]
