# Generated by Django 6.0.8 on 2026-09-26 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_20260926_0825'),
        ('users', '0012_merge_20260926_0833'),
    ]

    operations = [
    ]
