# Generated by Django 6.0.8 on 2026-09-30 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_organization_notify_match_changes'),
        ('users', '0013_merge_20260926_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(blank=True, help_text='Categorías de contenido que deseas ver en este club', related_name='category_preferences', to='core.category', verbose_name='Categorías de Interés')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_preferences', to='core.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de categorías',
                'verbose_name_plural': 'Preferencias de categorías',
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
