# Generated by Django 6.0.8 on 2026-09-30 10:19

from django.db import migrations


def copy_global_preferences_to_organizations(apps, schema_editor):
    """Reparte las categorías preferidas globales por cada club del usuario.

    El M2M antiguo ``User.preferred_categories`` no distinguía organización, así
    que se copia el conjunto actual a cada membresía del usuario para no perder
    preferencias y conservar el comportamiento previo. A partir de aquí cada
    club puede divergir.
    """
    User = apps.get_model('users', 'User')
    Membership = apps.get_model('users', 'Membership')
    CategoryPreference = apps.get_model('users', 'CategoryPreference')

    users = User.objects.filter(preferred_categories__isnull=False).distinct()
    for user in users:
        category_ids = list(user.preferred_categories.values_list('id', flat=True))
        organization_ids = Membership.objects.filter(
            user_id=user.pk
        ).values_list('organization_id', flat=True)
        for organization_id in organization_ids:
            preference, _ = CategoryPreference.objects.get_or_create(
                user_id=user.pk, organization_id=organization_id
            )
            preference.categories.set(category_ids)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_categorypreference'),
    ]

    operations = [
        migrations.RunPython(
            copy_global_preferences_to_organizations,
            migrations.RunPython.noop,
        ),
    ]
