# Generated by Django 6.0.8 on 2026-09-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_backfill_category_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferred_categories',
        ),
    ]
