# Generated by Django 6.0.8 on 2026-10-01 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_organization_notify_match_changes'),
        ('users', '0016_remove_user_preferred_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(help_text='URL de entrega proporcionada por el servicio Push del navegador (FCM, Apple APNs, etc.)', unique=True, verbose_name='Push Service Endpoint')),
                ('p256dh', models.CharField(max_length=255, verbose_name='Clave Pública P-256 (Dispositivo)')),
                ('auth', models.CharField(max_length=255, verbose_name='Token de Autenticación Criptográfica')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_push_subscriptions', to='core.organization', verbose_name='Organización / Club')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='web_push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Suscripción Web Push',
                'verbose_name_plural': 'Suscripciones Web Push',
                'indexes': [models.Index(fields=['organization', 'user'], name='users_webpu_organiz_f6d2d6_idx')],
            },
        ),
    ]
