# Generated by Django 6.0.8 on 2026-10-01 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_organization_notify_match_changes'),
        ('users', '0017_webpushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('match_result', 'Resultados de partidos'), ('new_album', 'Nuevos álbumes de fotos'), ('match_change', 'Cambios de horario o pista'), ('match_reminder', 'Recordatorios previos al partido'), ('match_media', 'Fotos y vídeos de partidos')], max_length=32, verbose_name='Tipo de notificación')),
                ('is_enabled', models.BooleanField(default=True, help_text='Indica si el usuario desea recibir este tipo de notificación.', verbose_name='Activado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='core.organization', verbose_name='Organización / Club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencia de notificación',
                'verbose_name_plural': 'Preferencias de notificaciones',
                'indexes': [models.Index(fields=['organization', 'notification_type', 'is_enabled'], name='users_notif_organiz_238f91_idx')],
                'unique_together': {('user', 'organization', 'notification_type')},
            },
        ),
    ]
