# Generated by Django 6.0.8 on 2026-10-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_notificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('es', 'Español'), ('ca', 'Català')], default='es', help_text='Idioma en el que se muestra la interfaz.', max_length=5, verbose_name='Idioma preferido'),
        ),
    ]
