# Generated by Django 6.0.8 on 2026-10-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('es', 'Español'), ('ca', 'Català')], default='', help_text='Idioma en el que se muestra la interfaz. Vacío: el del navegador.', max_length=5, verbose_name='Idioma preferido'),
        ),
    ]
