# Generated by Django 6.0.8 on 2026-10-02 14:36

from django.db import migrations


def clear_default_language(apps, schema_editor):
    # 0019 dio 'es' a todos sin que nadie lo eligiera; vacío = seguir el idioma del navegador.
    apps.get_model('users', 'User').objects.filter(preferred_language='es').update(preferred_language='')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_user_preferred_language'),
    ]

    operations = [
        migrations.RunPython(clear_default_language, migrations.RunPython.noop),
    ]
