# Generated by Django 6.0.8 on 2026-10-02 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_backfill_santjosep_gradient_color'),
        ('users', '0021_reset_default_preferred_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPushAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(blank=True, default='', max_length=64, verbose_name='Tipo de notificación')),
                ('match_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ID de partido')),
                ('candidates_count', models.PositiveIntegerField(default=0, verbose_name='Dispositivos candidatos')),
                ('dispatched_count', models.PositiveIntegerField(default=0, verbose_name='Enviados')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Fallidos')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_push_audits', to='core.organization', verbose_name='Organización / Club')),
            ],
            options={
                'verbose_name': 'Auditoría de aviso push',
                'verbose_name_plural': 'Auditorías de avisos push',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'notification_type', '-created_at'], name='users_webpu_organiz_4ab75b_idx')],
            },
        ),
    ]
