# Generated by Django 6.0.8 on 2026-10-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_webpushaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inactivity_warning_level',
            field=models.PositiveSmallIntegerField(default=0, help_text='0: sin aviso, 1: primer aviso (30 días), 2: aviso final (7 días)', verbose_name='Nivel de aviso de inactividad'),
        ),
        migrations.AddField(
            model_name='user',
            name='inactivity_warning_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha del último aviso de inactividad'),
        ),
    ]
