# Generated by Django 6.0.8 on 2026-10-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_inactivity_warning_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reactivation_requested_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en que una cuenta desactivada pidió volver a ser revisada.', null=True, verbose_name='Solicitud de reactivación'),
        ),
    ]
