# Generated by Django 6.0.8 on 2026-10-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_gender'),
        ('users', '0025_deactivate_inactive_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypreference',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='followers', to='teams.team', verbose_name='Mis equipos'),
        ),
    ]
