# Generated by Django 6.0.8 on 2026-10-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_notificationpreference_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('match_result', 'Resultados de partidos'), ('new_album', 'Nuevos álbumes de fotos'), ('match_change', 'Cambios de horario o pista'), ('match_reminder', 'Recordatorios previos al partido'), ('match_media', 'Fotos y vídeos de partidos'), ('match_photos', 'Recordatorio para subir fotos del partido'), ('image_tag', 'Avisos de etiquetado en fotos')], max_length=32, verbose_name='Tipo de notificación'),
        ),
    ]
