# Generated by Django 5.2.7 on 2025-10-05 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_league_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federation_id', models.CharField(max_length=200, unique=True)),
                ('official_name', models.CharField(max_length=200)),
                ('president', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('venue_name', models.CharField(blank=True, max_length=200)),
                ('venue_address', models.CharField(blank=True, max_length=200)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubes',
                'ordering': ['official_name'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='sponsor_name',
            field=models.CharField(blank=True, help_text='Nombre con patrocinador si aplica', max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='videos.club'),
        ),
    ]
