# Generated by Django 5.2.7 on 2025-10-05 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_club_team_sponsor_name_team_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Categoría asignada automáticamente durante el scraping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='videos.category'),
        ),
    ]
