# Generated by Django 5.2.7 on 2025-10-08 17:57

import django.core.validators
import videosvoley.videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_change_image_category_to_many_to_many'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='original_format',
            field=models.CharField(blank=True, help_text='Formato original del archivo (ej: heic, jpg)', max_length=10),
        ),
        migrations.AddField(
            model_name='image',
            name='was_converted',
            field=models.BooleanField(default=False, help_text='Indica si la imagen fue convertida desde otro formato'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='Formatos permitidos: JPG, PNG, WebP, HEIC. Tamaño máximo: 10MB', upload_to=videosvoley.videos.models.image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'heic', 'heif'])]),
        ),
    ]
