# Generated by Django 5.2.7 on 2025-10-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_image_original_format_image_was_converted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el equipo sigue activo en las competiciones'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programado'), ('in_progress', 'En Progreso'), ('finished', 'Finalizado'), ('postponed', 'Aplazado'), ('cancelled', 'Cancelado'), ('withdrawn', 'Retirado (equipo fuera de liga)')], default='scheduled', max_length=20),
        ),
    ]
