# Generated by Django 5.2.7 on 2025-10-11 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0016_team_is_active_alter_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_team_text',
            field=models.CharField(blank=True, help_text='Nombre del equipo visitante para partidos amistosos sin equipo en BD', max_length=200),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_text',
            field=models.CharField(blank=True, help_text='Nombre del equipo local para partidos amistosos sin equipo en BD', max_length=200),
        ),
        migrations.AddField(
            model_name='match',
            name='is_friendly',
            field=models.BooleanField(default=False, help_text='Indica si es un partido amistoso creado manualmente'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='videos.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='videos.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='videos.league'),
        ),
    ]
