# Generated by Django 5.2.7 on 2025-10-11 19:18

import django.core.validators
import django.db.models.deletion
import videosvoley.videos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0018_ensure_team_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('jersey_number', models.PositiveSmallIntegerField(blank=True, help_text='Número de la camiseta (opcional)', null=True, verbose_name='Número de Dorsal')),
                ('position', models.CharField(blank=True, choices=[('setter', 'Colocador/a'), ('outside_hitter', 'Atacante Receptor'), ('middle_blocker', 'Central'), ('opposite', 'Opuesto'), ('libero', 'Líbero'), ('universal', 'Universal')], help_text='Posición principal del jugador (opcional)', max_length=20, verbose_name='Posición')),
                ('birth_date', models.DateField(blank=True, help_text='Fecha de nacimiento del jugador (opcional)', null=True, verbose_name='Fecha de Nacimiento')),
                ('photo', models.ImageField(blank=True, help_text='Foto del jugador (opcional)', null=True, upload_to=videosvoley.videos.models.player_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Foto')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el jugador está actualmente en el equipo', verbose_name='Activo')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el jugador', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='videos.team', verbose_name='Equipo')),
                ('user', models.OneToOneField(blank=True, help_text='Usuario de la plataforma asociado al jugador (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Vinculado')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['jersey_number', 'last_name', 'first_name'],
                'indexes': [models.Index(fields=['team', 'is_active'], name='videos_play_team_id_22582d_idx'), models.Index(fields=['position'], name='videos_play_positio_3227e5_idx')],
                'unique_together': {('team', 'jersey_number')},
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('role', models.CharField(choices=[('head_coach', 'Entrenador/a Principal'), ('assistant_coach', 'Segundo Entrenador/a'), ('delegate', 'Delegado/a'), ('physical_trainer', 'Preparador/a Físico'), ('physiotherapist', 'Fisioterapeuta'), ('doctor', 'Médico/a'), ('manager', 'Manager'), ('other', 'Otro')], help_text='Función que desempeña en el equipo', max_length=20, verbose_name='Rol')),
                ('photo', models.ImageField(blank=True, help_text='Foto del miembro del staff (opcional)', null=True, upload_to=videosvoley.videos.models.staff_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Foto')),
                ('phone', models.CharField(blank=True, help_text='Número de contacto (opcional)', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico de contacto (opcional)', max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el miembro del staff está actualmente en el equipo', verbose_name='Activo')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el miembro del staff', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='videos.team', verbose_name='Equipo')),
                ('user', models.OneToOneField(blank=True, help_text='Usuario de la plataforma asociado al miembro del staff (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Vinculado')),
            ],
            options={
                'verbose_name': 'Miembro del Staff',
                'verbose_name_plural': 'Staff',
                'ordering': ['role', 'last_name', 'first_name'],
                'indexes': [models.Index(fields=['team', 'is_active'], name='videos_staf_team_id_a6dfe4_idx'), models.Index(fields=['role'], name='videos_staf_role_427190_idx')],
            },
        ),
    ]
