# Generated by Django 5.2.7 on 2025-10-12 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0021_migrate_player_staff_to_person_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Ficha', 'verbose_name_plural': 'Fichas'},
        ),
    ]
