# Generated by Django 5.2.7 on 2025-10-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0022_alter_person_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='delegate',
            field=models.CharField(blank=True, max_length=200, verbose_name='Delegado'),
        ),
        migrations.AddField(
            model_name='match',
            name='federation_club_away_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID Club Visitante (Federación)'),
        ),
        migrations.AddField(
            model_name='match',
            name='federation_club_local_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID Club Local (Federación)'),
        ),
        migrations.AddField(
            model_name='match',
            name='field_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Dirección del Campo'),
        ),
        migrations.AddField(
            model_name='match',
            name='referee1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Árbitro 1'),
        ),
        migrations.AddField(
            model_name='match',
            name='referee2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Árbitro 2'),
        ),
        migrations.AddField(
            model_name='match',
            name='scorer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Anotador'),
        ),
        migrations.AddField(
            model_name='match',
            name='timekeeper',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cronometrador'),
        ),
    ]
