# Generated by Django 5.2.7 on 2025-10-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0023_match_delegate_match_federation_club_away_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='acta_html',
            field=models.CharField(blank=True, max_length=200, verbose_name='Acta HTML'),
        ),
    ]
