# Generated by Django 5.2.7 on 2026-01-02 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0029_add_league_phases_and_team_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categorías de la liga (puede ser múltiple para torneos/copas)', related_name='leagues', to='videos.category'),
        ),
        migrations.AlterField(
            model_name='league',
            name='category',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Usar categories', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues_old', to='videos.category'),
        ),
    ]
