# Generated by Django 5.2.7 on 2026-06-02 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_organization_options_and_more'),
        ('videos', '0031_migrate_category_to_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='core.organization', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='video',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='core.organization', verbose_name='Organización'),
        ),
    ]
