# Generated by Django 6.0.8 on 2026-09-19 20:15

from django.db import migrations


def update_contenttypes(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ContentType.objects.filter(
        app_label='videos',
        model='category'
    ).update(app_label='core')


def revert_contenttypes(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ContentType.objects.filter(
        app_label='core',
        model='category'
    ).update(app_label='videos')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_move_category_to_core'),
        ('teams', '0002_alter_team_category'),
        ('competitions', '0002_alter_league_categories_alter_league_category'),
        ('content', '0003_alter_image_categories_alter_video_category'),
        ('users', '0010_alter_user_preferred_categories'),
        ('videos', '0040_move_competitions_to_app'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Category',
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(update_contenttypes, revert_contenttypes),
    ]
