# Generated by Django 6.0.8 on 2026-09-19 11:38

import django.core.validators
import django.db.models.deletion
import videosvoley.rosters.models.legacy
import videosvoley.rosters.models.rosters
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0036_set_explicit_db_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Nombre de la persona', max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(help_text='Apellidos de la persona', max_length=100, verbose_name='Apellidos')),
                ('birth_date', models.DateField(blank=True, help_text='Fecha de nacimiento (opcional)', null=True, verbose_name='Fecha de Nacimiento')),
                ('photo', models.ImageField(blank=True, help_text='Foto de la persona (opcional)', null=True, upload_to=videosvoley.rosters.models.rosters.person_photo_upload_path, verbose_name='Foto')),
                ('email', models.EmailField(blank=True, help_text='Dirección de email (opcional)', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Número de teléfono (opcional)', max_length=20, verbose_name='Teléfono')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre la persona', verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, help_text='¿Está activo en el club?', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('user', models.OneToOneField(blank=True, help_text='Usuario de la plataforma asociado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Vinculado')),
            ],
            options={
                'verbose_name': 'Ficha',
                'verbose_name_plural': 'Fichas',
                'db_table': 'videos_person',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('jersey_number', models.PositiveSmallIntegerField(blank=True, help_text='Número de la camiseta (opcional)', null=True, verbose_name='Número de Dorsal')),
                ('position', models.CharField(blank=True, choices=[('setter', 'Colocador'), ('outside_hitter', 'Receptor'), ('middle_blocker', 'Central'), ('opposite', 'Opuesto'), ('libero', 'Líbero')], help_text='Posición principal del jugador (opcional)', max_length=20, verbose_name='Posición')),
                ('birth_date', models.DateField(blank=True, help_text='Fecha de nacimiento del jugador (opcional)', null=True, verbose_name='Fecha de Nacimiento')),
                ('photo', models.ImageField(blank=True, help_text='Foto del jugador (opcional)', null=True, upload_to=videosvoley.rosters.models.legacy.player_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Foto')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el jugador está actualmente en el equipo', verbose_name='Activo')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el jugador', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='videos.team', verbose_name='Equipo')),
                ('user', models.OneToOneField(blank=True, help_text='Usuario de la plataforma asociado al jugador (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Vinculado')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'videos_player',
                'ordering': ['jersey_number', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.PositiveSmallIntegerField(blank=True, help_text='Número de la camiseta (opcional)', null=True, verbose_name='Número de Dorsal')),
                ('position', models.CharField(blank=True, choices=[('setter', 'Colocador'), ('outside_hitter', 'Receptor'), ('middle_blocker', 'Central'), ('opposite', 'Opuesto'), ('libero', 'Líbero')], help_text='Posición preferida (opcional)', max_length=20, verbose_name='Posición')),
                ('is_active', models.BooleanField(default=True, help_text='¿Está actualmente jugando en este equipo?', verbose_name='Activo')),
                ('notes', models.TextField(blank=True, help_text='Notas específicas sobre este rol', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_roles', to='rosters.person', verbose_name='Persona')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_roles', to='videos.team', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Rol de Jugador',
                'verbose_name_plural': 'Roles de Jugador',
                'db_table': 'videos_playerrole',
                'ordering': ['team', 'jersey_number', 'person__last_name', 'person__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('role', models.CharField(choices=[('head_coach', 'Entrenador/a'), ('assistant_coach', 'Segundo Entrenador/a'), ('delegate', 'Delegado/a'), ('other', 'Otro')], help_text='Función que desempeña en el equipo', max_length=20, verbose_name='Rol')),
                ('photo', models.ImageField(blank=True, help_text='Foto del miembro del staff (opcional)', null=True, upload_to=videosvoley.rosters.models.legacy.staff_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Foto')),
                ('phone', models.CharField(blank=True, help_text='Número de contacto (opcional)', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico de contacto (opcional)', max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el miembro del staff está actualmente en el equipo', verbose_name='Activo')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el miembro del staff', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='videos.team', verbose_name='Equipo')),
                ('user', models.OneToOneField(blank=True, help_text='Usuario de la plataforma asociado al miembro del staff (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Vinculado')),
            ],
            options={
                'verbose_name': 'Miembro del Staff',
                'verbose_name_plural': 'Staff',
                'db_table': 'videos_staff',
                'ordering': ['role', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('head_coach', 'Entrenador/a'), ('assistant_coach', 'Segundo Entrenador/a'), ('delegate', 'Delegado/a'), ('other', 'Otro')], help_text='Función que desempeña en el equipo', max_length=20, verbose_name='Rol')),
                ('is_active', models.BooleanField(default=True, help_text='¿Está actualmente trabajando con este equipo?', verbose_name='Activo')),
                ('notes', models.TextField(blank=True, help_text='Notas específicas sobre este rol', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to='rosters.person', verbose_name='Persona')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to='videos.team', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Rol de Staff',
                'verbose_name_plural': 'Roles de Staff',
                'db_table': 'videos_staffrole',
                'ordering': ['team', 'role', 'person__last_name', 'person__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['last_name', 'first_name'], name='videos_pers_last_na_2ba5e4_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_active'], name='videos_pers_is_acti_a5e18b_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['created_at'], name='videos_pers_created_4f369b_idx'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('birth_date__isnull', False)), fields=('first_name', 'last_name', 'birth_date'), name='unique_person_identity'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['team', 'is_active'], name='videos_play_team_id_22582d_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['position'], name='videos_play_positio_3227e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('team', 'jersey_number')},
        ),
        migrations.AddIndex(
            model_name='playerrole',
            index=models.Index(fields=['team', 'is_active'], name='videos_play_team_id_b4eaef_idx'),
        ),
        migrations.AddIndex(
            model_name='playerrole',
            index=models.Index(fields=['person', 'is_active'], name='videos_play_person__7da1a5_idx'),
        ),
        migrations.AddIndex(
            model_name='playerrole',
            index=models.Index(fields=['jersey_number'], name='videos_play_jersey__f60d05_idx'),
        ),
        migrations.AddIndex(
            model_name='playerrole',
            index=models.Index(fields=['position'], name='videos_play_positio_7dc98c_idx'),
        ),
        migrations.AddConstraint(
            model_name='playerrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('person', 'team'), name='unique_active_player_role'),
        ),
        migrations.AddConstraint(
            model_name='playerrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('jersey_number__isnull', False)), fields=('team', 'jersey_number'), name='unique_jersey_number_per_team'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['team', 'is_active'], name='videos_staf_team_id_a6dfe4_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['role'], name='videos_staf_role_427190_idx'),
        ),
        migrations.AddIndex(
            model_name='staffrole',
            index=models.Index(fields=['team', 'is_active'], name='videos_staf_team_id_7ddf73_idx'),
        ),
        migrations.AddIndex(
            model_name='staffrole',
            index=models.Index(fields=['person', 'is_active'], name='videos_staf_person__d528c0_idx'),
        ),
        migrations.AddIndex(
            model_name='staffrole',
            index=models.Index(fields=['role'], name='videos_staf_role_2f32b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('person', 'team', 'role'), name='unique_active_staff_role'),
        ),
            ],
            database_operations=[],
        ),
    ]
