# Generated by Django 6.0.8 on 2026-09-19 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.team', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='playerrole',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_roles', to='teams.team', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='teams.team', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='staffrole',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to='teams.team', verbose_name='Equipo'),
        ),
    ]
