# Generated by Django 6.0.8 on 2026-09-25 17:40
# Ajustada a mano: la FK a Organization se añade nullable, se rellena a partir
# de los roles de cada persona (PlayerRole/StaffRole -> Team.club -> Organization)
# y después se vuelve obligatoria.

import django.db.models.deletion
from django.db import migrations, models


def _club_org_map(Organization):
    mapping = {}
    for org_id, club_id in (
        Organization.objects.exclude(club__isnull=True).values_list('id', 'club_id')
    ):
        # Si varias organizaciones comparten club, gana la primera por id.
        mapping.setdefault(club_id, org_id)
    return mapping


def backfill_person_organization(apps, schema_editor):
    Person = apps.get_model('rosters', 'Person')
    PlayerRole = apps.get_model('rosters', 'PlayerRole')
    StaffRole = apps.get_model('rosters', 'StaffRole')
    Team = apps.get_model('teams', 'Team')
    Organization = apps.get_model('core', 'Organization')

    pending = Person.objects.filter(organization__isnull=True)
    if not pending.exists():
        return

    club_org = _club_org_map(Organization)

    # team_id -> org_id para los equipos con club vinculado a una organización.
    team_org = {}
    for team_id, club_id in Team.objects.exclude(club__isnull=True).values_list('id', 'club_id'):
        org_id = club_org.get(club_id)
        if org_id is not None:
            team_org[team_id] = org_id

    # Fallback determinista para fichas sin roles resolubles: la organización
    # de menor id (en la práctica el club principal / único).
    default_org_id = Organization.objects.order_by('id').values_list('id', flat=True).first()

    for person_id in pending.values_list('id', flat=True).iterator():
        team_ids = set(
            PlayerRole.objects.filter(person_id=person_id).values_list('team_id', flat=True)
        ) | set(
            StaffRole.objects.filter(person_id=person_id).values_list('team_id', flat=True)
        )

        counts = {}
        for team_id in team_ids:
            org_id = team_org.get(team_id)
            if org_id is not None:
                counts[org_id] = counts.get(org_id, 0) + 1

        if counts:
            # El club con más roles; empate -> organización de menor id.
            org_id = min(counts.items(), key=lambda item: (-item[1], item[0]))[0]
        else:
            org_id = default_org_id

        if org_id is not None:
            Person.objects.filter(pk=person_id).update(organization_id=org_id)


def reverse_backfill_person_organization(apps, schema_editor):
    # Al revertir se elimina la columna; no hay nada que restaurar.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_organization_default_home'),
        ('rosters', '0005_remove_playerrole_unique_active_player_role_and_more'),
        # Necesaria para que Team.club esté backfilleado antes de resolver la
        # organización de cada ficha a partir de sus roles.
        ('teams', '0003_backfill_team_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='organization',
            field=models.ForeignKey(help_text='Club/organización al que pertenece la ficha', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='core.organization', verbose_name='Organización'),
        ),
        migrations.RunPython(
            backfill_person_organization,
            reverse_backfill_person_organization,
        ),
        migrations.AlterField(
            model_name='person',
            name='organization',
            field=models.ForeignKey(help_text='Club/organización al que pertenece la ficha', on_delete=django.db.models.deletion.PROTECT, related_name='people', to='core.organization', verbose_name='Organización'),
        ),
    ]
