# Generated by Django 6.0.8 on 2026-09-25 17:40
# Ajustada a mano: la FK a Organization se añade nullable y se rellena solo
# cuando la pertenencia es inequívoca (los equipos de todos sus roles apuntan a
# una única organización). Las fichas sin roles resolubles o con roles en varias
# organizaciones quedan sin asignar (organization NULL) y, por tanto, ocultas en
# todos los tenants: no se inventa pertenencia.

import django.db.models.deletion
from django.db import migrations, models


def backfill_person_organization(apps, schema_editor):
    Person = apps.get_model('rosters', 'Person')
    PlayerRole = apps.get_model('rosters', 'PlayerRole')
    StaffRole = apps.get_model('rosters', 'StaffRole')
    Team = apps.get_model('teams', 'Team')
    Organization = apps.get_model('core', 'Organization')

    pending_ids = list(
        Person.objects.filter(organization__isnull=True).values_list('id', flat=True)
    )
    if not pending_ids:
        return

    # club_id -> organization_id (si varias organizaciones comparten club,
    # la primera por id). Un club sin organización vinculada no resuelve.
    club_org = {}
    for org_id, club_id in (
        Organization.objects.exclude(club__isnull=True).values_list('id', 'club_id')
    ):
        club_org.setdefault(club_id, org_id)

    # team_id -> org_id para los equipos con club vinculado a una organización.
    team_org = {}
    for team_id, club_id in Team.objects.exclude(club__isnull=True).values_list('id', 'club_id'):
        org_id = club_org.get(club_id)
        if org_id is not None:
            team_org[team_id] = org_id

    for person_id in pending_ids:
        team_ids = set(
            PlayerRole.objects.filter(person_id=person_id).values_list('team_id', flat=True)
        ) | set(
            StaffRole.objects.filter(person_id=person_id).values_list('team_id', flat=True)
        )
        org_ids = {team_org[team_id] for team_id in team_ids if team_id in team_org}
        # Solo se asigna si todos los roles apuntan a una única organización.
        if len(org_ids) == 1:
            org_id = org_ids.pop()
            Person.objects.filter(pk=person_id).update(organization_id=org_id)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_organization_default_home'),
        ('rosters', '0005_remove_playerrole_unique_active_player_role_and_more'),
        # Necesaria para que Team.club esté backfilleado antes de resolver la
        # organización de cada ficha a partir de sus roles.
        ('teams', '0003_backfill_team_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Club/organización al que pertenece la ficha', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='core.organization', verbose_name='Organización'),
        ),
        migrations.RunPython(
            backfill_person_organization,
            migrations.RunPython.noop,
        ),
    ]
