# Generated by Django 6.0.8 on 2026-09-27 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_organization_default_home'),
        ('rosters', '0006_person_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='person',
            name='unique_person_identity',
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('birth_date__isnull', False)), fields=('organization', 'first_name', 'last_name', 'birth_date'), name='unique_person_identity', nulls_distinct=False),
        ),
    ]
