# Generated by Django 6.0.8 on 2026-10-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_backfill_santjosep_gradient_color'),
        ('rosters', '0007_remove_person_unique_person_identity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Año de nacimiento; se rellena solo si hay fecha de nacimiento', null=True, verbose_name='Año de Nacimiento'),
        ),
        migrations.AddField(
            model_name='person',
            name='organizations',
            field=models.ManyToManyField(blank=True, help_text='Clubes/organizaciones vinculados a la ficha', related_name='linked_people', to='core.organization', verbose_name='Organizaciones'),
        ),
    ]
