# Generated by Django 6.0.8 on 2026-10-04 20:57

from django.db import migrations
from django.db.models.functions import ExtractYear


def backfill(apps, schema_editor):
    Person = apps.get_model('rosters', 'Person')
    Person.objects.filter(birth_date__isnull=False).update(birth_year=ExtractYear('birth_date'))
    # La organización de alta pasa al M2M (ahora el FK deja de ser la fuente).
    for person in Person.objects.filter(organization__isnull=False).only('id', 'organization_id'):
        person.organizations.add(person.organization_id)


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0008_person_birth_year_organizations'),
    ]

    operations = [
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
