# Generated by Django 6.0.8 on 2026-10-04 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_backfill_santjosep_gradient_color'),
        ('rosters', '0009_backfill_birth_year_organizations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='person',
            name='unique_person_identity',
        ),
        migrations.AlterField(
            model_name='person',
            name='organizations',
            field=models.ManyToManyField(blank=True, help_text='Clubes/organizaciones vinculados a la ficha', related_name='people', to='core.organization', verbose_name='Organizaciones'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'birth_year'), name='unique_person_identity', violation_error_message='Ya existe una ficha con ese nombre, apellidos y año de nacimiento.'),
        ),
        migrations.RemoveField(
            model_name='person',
            name='organization',
        ),
    ]
