# Generated by Django 6.0.8 on 2026-10-09 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0010_person_global_identity'),
        ('teams', '0010_backfill_team_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerrole',
            name='identity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_roles', to='teams.teamidentity', verbose_name='Equipo'),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='identity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_roles', to='teams.teamidentity', verbose_name='Equipo'),
        ),
    ]
