# Generated by Django 6.0.8 on 2026-10-09 05:05

from django.db import migrations


def _dedupe(model, key_fields):
    """Un rol por clave (identidad, temporada, persona[, rol]): gana el último estado.

    Un cambio de posición o dorsal entre fases de la misma temporada es normal;
    el rol guarda solo el último (#447, §4).
    """
    seen = set()
    for role in model.objects.order_by('-is_active', '-updated_at', '-id'):
        key = tuple(getattr(role, f) for f in key_fields)
        if key in seen:
            role.delete()
        else:
            seen.add(key)


def forwards(apps, schema_editor):
    PlayerRole = apps.get_model('rosters', 'PlayerRole')
    StaffRole = apps.get_model('rosters', 'StaffRole')
    for model in (PlayerRole, StaffRole):
        orphans = list(model.objects.filter(team__identity__isnull=True).values_list('id', flat=True))
        if orphans:
            raise RuntimeError(f'{model.__name__} con equipo sin identidad: {orphans}. Asignarla antes de migrar.')
        for role in model.objects.select_related('team'):
            role.identity_id = role.team.identity_id
            role.save(update_fields=['identity'])

    _dedupe(PlayerRole, ('identity_id', 'season_id', 'person_id'))
    _dedupe(StaffRole, ('identity_id', 'season_id', 'person_id', 'role'))

    jerseys = {}
    for role in PlayerRole.objects.filter(is_active=True, jersey_number__isnull=False):
        jerseys.setdefault((role.identity_id, role.season_id, role.jersey_number), []).append(role.id)
    clashes = [ids for ids in jerseys.values() if len(ids) > 1]
    if clashes:
        raise RuntimeError(f'Dorsal repetido con personas distintas al unificar por identidad: {clashes}')


def backwards(apps, schema_editor):
    """Devuelve cada rol a la fila más reciente de su identidad (activa si la hay)."""
    Team = apps.get_model('teams', 'Team')
    for model in (apps.get_model('rosters', 'PlayerRole'), apps.get_model('rosters', 'StaffRole')):
        for role in model.objects.all():
            role.team = Team.objects.filter(identity_id=role.identity_id).order_by('-is_active', '-id').first()
            role.save(update_fields=['team'])


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0011_role_identity'),
        ('teams', '0010_backfill_team_identity'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
