# Generated by Django 6.0.8 on 2026-10-09 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_backfill_santjosep_gradient_color'),
        ('rosters', '0012_backfill_role_identity'),
        ('teams', '0010_backfill_team_identity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerrole',
            options={'ordering': ['identity', 'jersey_number', 'person__last_name', 'person__first_name'], 'verbose_name': 'Rol de Jugador', 'verbose_name_plural': 'Roles de Jugador'},
        ),
        migrations.AlterModelOptions(
            name='staffrole',
            options={'ordering': ['identity', 'role', 'person__last_name', 'person__first_name'], 'verbose_name': 'Rol de Staff', 'verbose_name_plural': 'Roles de Staff'},
        ),
        migrations.RemoveConstraint(
            model_name='playerrole',
            name='unique_active_player_role',
        ),
        migrations.RemoveConstraint(
            model_name='playerrole',
            name='unique_jersey_number_per_team',
        ),
        migrations.RemoveConstraint(
            model_name='staffrole',
            name='unique_active_staff_role',
        ),
        migrations.RemoveIndex(
            model_name='playerrole',
            name='videos_play_team_id_b4eaef_idx',
        ),
        migrations.RemoveIndex(
            model_name='staffrole',
            name='videos_staf_team_id_7ddf73_idx',
        ),
        migrations.AlterField(
            model_name='playerrole',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_roles', to='teams.teamidentity', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='staffrole',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_roles', to='teams.teamidentity', verbose_name='Equipo'),
        ),
        migrations.AddIndex(
            model_name='playerrole',
            index=models.Index(fields=['identity', 'is_active'], name='videos_play_identit_eea4cd_idx'),
        ),
        migrations.AddIndex(
            model_name='staffrole',
            index=models.Index(fields=['identity', 'is_active'], name='videos_staf_identit_22b51e_idx'),
        ),
        migrations.AddConstraint(
            model_name='playerrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('person', 'identity', 'season'), name='unique_active_player_role'),
        ),
        migrations.AddConstraint(
            model_name='playerrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('jersey_number__isnull', False)), fields=('identity', 'season', 'jersey_number'), name='unique_jersey_number_per_team'),
        ),
        migrations.AddConstraint(
            model_name='staffrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('person', 'identity', 'role', 'season'), name='unique_active_staff_role'),
        ),
    ]
