# Generated by Django 6.0.8 on 2026-10-09 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0013_role_identity_constraints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerrole',
            name='team',
        ),
        migrations.RemoveField(
            model_name='staffrole',
            name='team',
        ),
    ]
