# Generated by Django 6.0.8 on 2026-10-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0014_remove_role_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image_consent',
            field=models.CharField(choices=[('none', 'Sin consentimiento'), ('internal_only', 'Solo uso interno del club'), ('full_public', 'Uso público')], default='internal_only', help_text='Uso de la imagen autorizado por el deportista o su familia', max_length=20, verbose_name='Consentimiento de imagen'),
        ),
        migrations.AddField(
            model_name='person',
            name='image_consent_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Consentimiento actualizado'),
        ),
    ]
