# Generated by Django 6.0.8 on 2026-10-09 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_backfill_santjosep_gradient_color'),
        ('rosters', '0015_person_image_consent_person_image_consent_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='¿Está la ficha dada de alta en el club?', verbose_name='Activa')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_memberships', to='core.organization', verbose_name='Organización')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to='rosters.person', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Pertenencia a club',
                'verbose_name_plural': 'Pertenencias a club',
                'ordering': ['person__last_name', 'person__first_name'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='rosters_per_organiz_25b05b_idx')],
                'constraints': [models.UniqueConstraint(fields=('person', 'organization'), name='unique_person_organization')],
            },
        ),
    ]
