# Generated by Django 6.0.8 on 2026-10-09 21:00

from django.db import migrations


def backfill_person_organization(apps, schema_editor):
    """Copia la M2M `videos_person_organizations` al nuevo through (#478).

    Se ejecuta antes de alterar el campo a `through`: cuando Django suelte la
    tabla auto-generada, todos los vínculos ya estarán en PersonOrganization.
    Cualquier fila ya existente (migración re-ejecutada en un entorno atípico)
    se perdona con ignore_conflicts para no arrastrar estados manuales.
    """
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute('SELECT person_id, organization_id FROM videos_person_organizations')
        rows = cursor.fetchall()
    if not rows:
        return
    PersonOrganization = apps.get_model('rosters', 'PersonOrganization')
    PersonOrganization.objects.bulk_create(
        (PersonOrganization(person_id=p, organization_id=o, is_active=True) for p, o in rows),
        ignore_conflicts=True,
    )


def unbackfill_person_organization(apps, schema_editor):
    """Reversa parcial: se borran solo las filas re-creadas del backfill."""
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute('SELECT person_id, organization_id FROM videos_person_organizations')
        rows = cursor.fetchall()
    if rows:
        PersonOrganization = apps.get_model('rosters', 'PersonOrganization')
        PersonOrganization.objects.filter(person_id__in={p for p, _ in rows}, organization_id__in={o for _, o in rows}).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0016_personorganization'),
    ]

    operations = [
        migrations.RunPython(backfill_person_organization, unbackfill_person_organization),
    ]
