# Generated by Django 6.0.8 on 2026-10-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_backfill_santjosep_gradient_color'),
        ('rosters', '0017_backfill_person_organization'),
    ]

    operations = [
        # Django no admite AlterField de through automático a explícito
        # (ValueError en tiempo de migración), así que se separa la relación
        # y se re-crea con el through. Los datos ya están copiados a
        # PersonOrganization por 0017, que corre sobre la tabla original antes
        # de este RemoveField.
        migrations.RemoveField(
            model_name='person',
            name='organizations',
        ),
        migrations.AddField(
            model_name='person',
            name='organizations',
            field=models.ManyToManyField(blank=True, help_text='Clubes/organizaciones vinculados a la ficha', related_name='people', through='rosters.PersonOrganization', to='core.organization', verbose_name='Organizaciones'),
        ),
    ]
