# Generated by Django 6.0.8 on 2026-10-10 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_backfill_santjosep_gradient_color'),
        ('rosters', '0018_alter_person_organizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonWrapped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(default='indoor', max_length=10)),
                ('stats', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_wrappeds', to='rosters.person')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrappeds', to='core.season')),
            ],
            options={
                'ordering': ['-season__start_year'],
                'constraints': [models.UniqueConstraint(fields=('person', 'season', 'modality'), name='unique_wrapped_per_season_modality')],
            },
        ),
    ]
