# Generated by Django 5.2.7 on 2025-10-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ha sido aprobado por un administrador para acceder al contenido.'),
        ),
    ]
