# Generated by Django 5.2.7 on 2025-10-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_approved'),
        ('videos', '0013_image_auto_tags_image_image_type_image_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent_info',
            field=models.TextField(blank=True, help_text='Indica de qué niño/a eres padre/familiar (ej: "papá de Juanito de Infantil")', verbose_name='Información Familiar'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_categories',
            field=models.ManyToManyField(blank=True, help_text='Categorías de contenido que deseas ver', related_name='subscribed_users', to='videos.category', verbose_name='Categorías de Interés'),
        ),
    ]
