# Generated by Django 5.2.7 on 2025-10-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_parent_info_user_preferred_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calendar_last_sync',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la última sincronización con Google Calendar', null=True, verbose_name='Última Sincronización'),
        ),
        migrations.AddField(
            model_name='user',
            name='calendar_sync_enabled',
            field=models.BooleanField(default=False, help_text='Sincronizar automáticamente los partidos de tus categorías preferidas con Google Calendar', verbose_name='Sincronizar con Google Calendar'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_calendar_id',
            field=models.CharField(blank=True, help_text='ID del calendar específico donde sincronizar eventos (opcional, usa calendar principal si está vacío)', max_length=200, verbose_name='ID del Calendar de Google'),
        ),
    ]
