# Generated by Django 5.2.7 on 2025-10-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_calendar_last_sync_user_calendar_sync_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calendar_token',
            field=models.CharField(blank=True, null=True, help_text='Token único para suscribirse al calendario de partidos vía .ics', max_length=64, unique=True, verbose_name='Token de Suscripción al Calendario'),
        ),
    ]
