# Generated by Django 6.0.8 on 2026-09-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0001_initial'),
        ('users', '0008_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='children',
            field=models.ManyToManyField(blank=True, help_text='Fichas de los hijos que puedes editar', related_name='parents', to='rosters.person', verbose_name='Hijos'),
        ),
    ]
